package wowRetail_TechTalent
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetTechTalentTreeResponse is the unified BNet representation for TechTalentTree.
type BNetTechTalentTreeResponse struct{}

// TechTalentTreeResponse represents the raw CN API response for TechTalentTree.
type TechTalentTreeResponse BNetTechTalentTreeResponse

// ToBNet converts the CN response to the unified BNetTechTalentTreeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *TechTalentTreeResponse) ToBNet() any {
	return r 
}

