package wow_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: PvPSeasonsIndex
// ==============================================================================================

type PvPSeasonsIndexFields struct {
	Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookPvPSeasonsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookPvPSeasonsIndex func(context.Context, *PvPSeasonsIndexFields) (any, error)

// StringPvPSeasonsIndex executes the request and returns the raw response body string.
func StringPvPSeasonsIndex(ctx context.Context, fields *PvPSeasonsIndexFields) (string, error) {
	if fields == nil {
		fields = &PvPSeasonsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("PvPSeasonsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/pvp-season/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgePvPSeasonsIndex routes the request to either CN or Global logic based on input.
func bridgePvPSeasonsIndex(ctx context.Context, fields *PvPSeasonsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookPvPSeasonsIndex != nil {
			return CNHookPvPSeasonsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringPvPSeasonsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &PvPSeasonsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// PvPSeasonsIndex
/* PvPSeasonsIndex Returns an index of PvP seasons. */
// Path: /data/wow/pvp-season/index
var PvPSeasonsIndex = bridgePvPSeasonsIndex


// ==============================================================================================
// API: PvPSeason
// ==============================================================================================

type PvPSeasonFields struct {
	PvpSeasonId int `uri:"pvpSeasonId" binding:"required"` // The ID of the PvP season.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookPvPSeason allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookPvPSeason func(context.Context, *PvPSeasonFields) (any, error)

// StringPvPSeason executes the request and returns the raw response body string.
func StringPvPSeason(ctx context.Context, fields *PvPSeasonFields) (string, error) {
	if fields == nil {
		fields = &PvPSeasonFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("PvPSeason")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/pvp-season/{pvpSeasonId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.PvpSeasonId == 0 {
		fields.PvpSeasonId = 33
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"pvpSeasonId": fields.PvpSeasonId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgePvPSeason routes the request to either CN or Global logic based on input.
func bridgePvPSeason(ctx context.Context, fields *PvPSeasonFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookPvPSeason != nil {
			return CNHookPvPSeason(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringPvPSeason(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &PvPSeasonModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// PvPSeason
/* PvPSeason Returns a PvP season by ID. */
// Path: /data/wow/pvp-season/{pvpSeasonId}
var PvPSeason = bridgePvPSeason


// ==============================================================================================
// API: PvPLeaderboardsIndex
// ==============================================================================================

type PvPLeaderboardsIndexFields struct {
	PvpSeasonId int `uri:"pvpSeasonId" binding:"required"` // The ID of the PvP season.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookPvPLeaderboardsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookPvPLeaderboardsIndex func(context.Context, *PvPLeaderboardsIndexFields) (any, error)

// StringPvPLeaderboardsIndex executes the request and returns the raw response body string.
func StringPvPLeaderboardsIndex(ctx context.Context, fields *PvPLeaderboardsIndexFields) (string, error) {
	if fields == nil {
		fields = &PvPLeaderboardsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("PvPLeaderboardsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.PvpSeasonId == 0 {
		fields.PvpSeasonId = 33
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"pvpSeasonId": fields.PvpSeasonId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgePvPLeaderboardsIndex routes the request to either CN or Global logic based on input.
func bridgePvPLeaderboardsIndex(ctx context.Context, fields *PvPLeaderboardsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookPvPLeaderboardsIndex != nil {
			return CNHookPvPLeaderboardsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringPvPLeaderboardsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &PvPLeaderboardsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// PvPLeaderboardsIndex
/* PvPLeaderboardsIndex Returns an index of PvP leaderboards for a PvP season. */
// Path: /data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/index
var PvPLeaderboardsIndex = bridgePvPLeaderboardsIndex


// ==============================================================================================
// API: PvPLeaderboard
// ==============================================================================================

type PvPLeaderboardFields struct {
	PvpSeasonId int `uri:"pvpSeasonId" binding:"required"` // The ID of the PvP season.
		PvpBracket string `uri:"pvpBracket" binding:"required"` // The PvP bracket type.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookPvPLeaderboard allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookPvPLeaderboard func(context.Context, *PvPLeaderboardFields) (any, error)

// StringPvPLeaderboard executes the request and returns the raw response body string.
func StringPvPLeaderboard(ctx context.Context, fields *PvPLeaderboardFields) (string, error) {
	if fields == nil {
		fields = &PvPLeaderboardFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("PvPLeaderboard")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.PvpSeasonId == 0 {
		fields.PvpSeasonId = 33
	}
	
	if fields.PvpBracket == "" {
		fields.PvpBracket = "3v3"
	}
	
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"pvpSeasonId": fields.PvpSeasonId,
    		"pvpBracket": fields.PvpBracket,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgePvPLeaderboard routes the request to either CN or Global logic based on input.
func bridgePvPLeaderboard(ctx context.Context, fields *PvPLeaderboardFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookPvPLeaderboard != nil {
			return CNHookPvPLeaderboard(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringPvPLeaderboard(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &PvPLeaderboardModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// PvPLeaderboard
/* PvPLeaderboard Returns the PvP leaderboard of a specific PvP bracket for a PvP season. */
// Path: /data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}
var PvPLeaderboard = bridgePvPLeaderboard


// ==============================================================================================
// API: PvPRewardsIndex
// ==============================================================================================

type PvPRewardsIndexFields struct {
	PvpSeasonId int `uri:"pvpSeasonId" binding:"required"` // The ID of the PvP season.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookPvPRewardsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookPvPRewardsIndex func(context.Context, *PvPRewardsIndexFields) (any, error)

// StringPvPRewardsIndex executes the request and returns the raw response body string.
func StringPvPRewardsIndex(ctx context.Context, fields *PvPRewardsIndexFields) (string, error) {
	if fields == nil {
		fields = &PvPRewardsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("PvPRewardsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/pvp-season/{pvpSeasonId}/pvp-reward/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.PvpSeasonId == 0 {
		fields.PvpSeasonId = 33
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"pvpSeasonId": fields.PvpSeasonId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgePvPRewardsIndex routes the request to either CN or Global logic based on input.
func bridgePvPRewardsIndex(ctx context.Context, fields *PvPRewardsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookPvPRewardsIndex != nil {
			return CNHookPvPRewardsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringPvPRewardsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &PvPRewardsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// PvPRewardsIndex
/* PvPRewardsIndex Returns an index of PvP rewards for a PvP season. */
// Path: /data/wow/pvp-season/{pvpSeasonId}/pvp-reward/index
var PvPRewardsIndex = bridgePvPRewardsIndex

