package updater

var apiTmpl = `package {{.PkgName}}
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
)





{{range .Apis}} 
//{{.Description}}
//@see: {{.Path}}

func String{{.Name}}(ctx context.Context  {{ if .Params}} ,
{{range .Params}}{{.Name}} {{.Type}}{{end}}
{{end}})(string,error){
	return "" , ApiError.ErrorInDevelopment
	client := utils.NewRequest()
	token := internal.TryToGetToken(slug, name)
	if token == ""{ 
		return "",ApiError.ErrorNoToken
	}

	return 	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "",  "token",token)
}
	
func CN{{.Name}}(ctx context.Context  {{ if .Params}} ,
{{range .Params}}{{.Name}} {{.Type}}{{end}}
{{end}})(any,error){

obj, err := String{{.Name}}(ctx {{ if .Params}} ,{{range .Params}}{{.Name}},{{end}}{{end}} )
if err != nil {
		return nil,err
	}
resp :=&{{.Name}}Response{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

func BNet{{.Name}}(ctx context.Context  {{ if .Params}} ,
{{range .Params}}{{.Name}} {{.Type}},{{end}}
{{end}})(any,error){

obj ,err := CN{{.Name}}(ctx {{ if .Params}} ,{{range .Params}}{{.Name}},{{end}}{{end}} )
if err != nil {
	return nil,err
}


return obj.(*{{.Name}}Response).ToBNet(),nil
}

{{end}}
`

var dataTmpl = `package {{.PkgName}}_{{.ApiGroupName}}
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

{{range .Apis}} 
//==============================================================================================

type {{.Name}}Fields struct{
	{{range .Params}}{{.Name}} {{.Type}}//{{.Description}}
	{{end}}
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func {{.Name}}Field(input *{{.Name}}Fields) *{{.Name}}Fields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "{{.Method}}",
//			Path: "{{.Path}}",
//			CnRegion:{{.CnRegion}} ,
//}
//return input
//}


//{{.Description}}
//
//@see: {{.Path}}
func String{{.Name}}(ctx context.Context, fields *{{.Name}}Fields)(string,error){
	if fields == nil {
		fields = &{{.Name}}Fields{}
	}

	func(input *{{.Name}}Fields) {
	{{range .Params}}{{if eq .Type "int"}}
if input.{{.Name}}==0{
input.{{.Name}} = {{.DefaultValue}}
}
	{{else}}
if input.{{.Name}}==""{
input.{{.Name}} = "{{.DefaultValue}}"
}
{{end}}
	{{end}}
		input.RequestMethod = utils.RequestMethod{
			Methods: "{{.Method}}",
			Path: "{{.Path}}",
			CnRegion:{{.CnRegion}} ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	{{range .Params}}q.Add("{{.ParamName}}", {{if eq .Type "int"}}strconv.Itoa(fields.{{.Name}}){{else}}fields.{{.Name}}{{end}})
	{{end}}
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CN{{.Name}}(ctx context.Context, fields *{{.Name}}Fields)(any,error){

obj, err := String{{.Name}}(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&{{.Name}}Response{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var {{.Name}} = CN{{.Name}}
/*func BNet{{.Name}}(ctx context.Context, fields *{{.Name}}Fields)(any,error){

obj ,err := CN{{.Name}}(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*{{.Name}}Response).ToBNet(),nil
}*/

{{end}}
`

var apiListTmpl = `
`

var modelTmpl = `package {{.PkgName}}_{{.ApiGroupName}}
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNet{{.Name}}Response is the unified BNet representation for {{.Name}}.
type BNet{{.Name}}Response struct{}

// {{.Name}}Response represents the raw CN API response for {{.Name}}.
type {{.Name}}Response BNet{{.Name}}Response

// ToBNet converts the CN response to the unified BNet{{.Name}}Response.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *{{.Name}}Response) ToBNet() any {
	return r 
}

`

// Silence unused variable warning; modelTmpl is intended for future use when generating per-API model files.
var _ = modelTmpl
