package wowRetail_Realm
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type RealmsIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func RealmsIndexField(input *RealmsIndexFields) *RealmsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/realm/index",
//			CnRegion:false ,
//}
//return input
//}


//RealmsIndex Returns an index of realms.
//
//@see: /data/wow/realm/index
func StringRealmsIndex(ctx context.Context, fields *RealmsIndexFields)(string,error){
	if fields == nil {
		fields = &RealmsIndexFields{}
	}

	func(input *RealmsIndexFields) {
	
if input.Namespace==""{
input.Namespace = "dynamic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/realm/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNRealmsIndex(ctx context.Context, fields *RealmsIndexFields)(any,error){

obj, err := StringRealmsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&RealmsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var RealmsIndex = CNRealmsIndex
/*func BNetRealmsIndex(ctx context.Context, fields *RealmsIndexFields)(any,error){

obj ,err := CNRealmsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*RealmsIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type RealmFields struct{
	RealmSlug string//The slug of the realm.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func RealmField(input *RealmFields) *RealmFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/realm/{realmSlug}",
//			CnRegion:false ,
//}
//return input
//}


//Realm Returns a single realm by slug or ID.
//
//@see: /data/wow/realm/{realmSlug}
func StringRealm(ctx context.Context, fields *RealmFields)(string,error){
	if fields == nil {
		fields = &RealmFields{}
	}

	func(input *RealmFields) {
	
if input.RealmSlug==""{
input.RealmSlug = "tichondrius"
}

	
if input.Namespace==""{
input.Namespace = "dynamic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/realm/{realmSlug}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNRealm(ctx context.Context, fields *RealmFields)(any,error){

obj, err := StringRealm(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&RealmResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Realm = CNRealm
/*func BNetRealm(ctx context.Context, fields *RealmFields)(any,error){

obj ,err := CNRealm(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*RealmResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type RealmSearchFields struct{
	Namespace string//The namespace to use to locate this document.
	Timezone string//The timezone of the realm. (example search field)
	Orderby string//The field to sort the result set by.
	_page int//The result page number.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func RealmSearchField(input *RealmSearchFields) *RealmSearchFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/search/realm",
//			CnRegion:false ,
//}
//return input
//}


//RealmSearch Performs a search of realms. The fields below are provided for example. For more detail see the <a href="/documentation/world-of-warcraft/guides/search">Search Guide</a>.
//
//@see: /data/wow/search/realm
func StringRealmSearch(ctx context.Context, fields *RealmSearchFields)(string,error){
	if fields == nil {
		fields = &RealmSearchFields{}
	}

	func(input *RealmSearchFields) {
	
if input.Namespace==""{
input.Namespace = "dynamic-us"
}

	
if input.Timezone==""{
input.Timezone = "America/New_York"
}

	
if input.Orderby==""{
input.Orderby = "id"
}

	
if input._page==0{
input._page = 1
}
	
	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/search/realm",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("timezone", fields.Timezone)
	q.Add("orderby", fields.Orderby)
	q.Add("_page", strconv.Itoa(fields._page))
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNRealmSearch(ctx context.Context, fields *RealmSearchFields)(any,error){

obj, err := StringRealmSearch(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&RealmSearchResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var RealmSearch = CNRealmSearch
/*func BNetRealmSearch(ctx context.Context, fields *RealmSearchFields)(any,error){

obj ,err := CNRealmSearch(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*RealmSearchResponse).ToBNet(),nil
}*/


