package wow_CharacterPvP
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetCharacterPvPBracketStatisticsResponse is the unified BNet representation for CharacterPvPBracketStatistics.
type BNetCharacterPvPBracketStatisticsResponse struct{}

// CharacterPvPBracketStatisticsResponse represents the raw CN API response for CharacterPvPBracketStatistics.
type CharacterPvPBracketStatisticsResponse BNetCharacterPvPBracketStatisticsResponse

// ToBNet converts the CN response to the unified BNetCharacterPvPBracketStatisticsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterPvPBracketStatisticsResponse) ToBNet() any {
	return r 
}

