package D3_D3
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetEraLeaderboardResponse is the unified BNet representation for EraLeaderboard.
type BNetEraLeaderboardResponse struct{}

// EraLeaderboardResponse represents the raw CN API response for EraLeaderboard.
type EraLeaderboardResponse BNetEraLeaderboardResponse

// ToBNet converts the CN response to the unified BNetEraLeaderboardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *EraLeaderboardResponse) ToBNet() any {
	return r 
}

