package wowRetail_Achievement
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAchievementCategoryResponse is the unified BNet representation for AchievementCategory.
type BNetAchievementCategoryResponse struct{}

// AchievementCategoryResponse represents the raw CN API response for AchievementCategory.
type AchievementCategoryResponse BNetAchievementCategoryResponse

// ToBNet converts the CN response to the unified BNetAchievementCategoryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AchievementCategoryResponse) ToBNet() any {
	return r 
}

