package wowRetail_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"

// BNetAchievementResponse is the unified BNet representation for Achievement.
type BNetAchievementResponse struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Achievements []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"achievements"`
}

// AchievementResponse represents the raw CN API response for Achievement.
type AchievementResponse BNetAchievementResponse

// ToBNet converts the CN response to the unified BNetAchievementResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AchievementResponse) ToBNet() any {
	return r
}
