package wowRetail_Achievement
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAchievementsIndexResponse is the unified BNet representation for AchievementsIndex.
type BNetAchievementsIndexResponse struct{}

// AchievementsIndexResponse represents the raw CN API response for AchievementsIndex.
type AchievementsIndexResponse BNetAchievementsIndexResponse

// ToBNet converts the CN response to the unified BNetAchievementsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AchievementsIndexResponse) ToBNet() any {
	return r 
}

