package wowRetail_ItemAppearance
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetItemAppearanceResponse is the unified BNet representation for ItemAppearance.
type BNetItemAppearanceResponse struct{}

// ItemAppearanceResponse represents the raw CN API response for ItemAppearance.
type ItemAppearanceResponse BNetItemAppearanceResponse

// ToBNet converts the CN response to the unified BNetItemAppearanceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *ItemAppearanceResponse) ToBNet() any {
	return r 
}

