package wow_ModifiedCrafting

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: ModifiedCraftingIndex
// ==============================================================================================

type ModifiedCraftingIndexFields struct {
	Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookModifiedCraftingIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookModifiedCraftingIndex func(context.Context, *ModifiedCraftingIndexFields) (any, error)

// StringModifiedCraftingIndex executes the request and returns the raw response body string.
func StringModifiedCraftingIndex(ctx context.Context, fields *ModifiedCraftingIndexFields) (string, error) {
	if fields == nil {
		fields = &ModifiedCraftingIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ModifiedCraftingIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/modified-crafting/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeModifiedCraftingIndex routes the request to either CN or Global logic based on input.
func bridgeModifiedCraftingIndex(ctx context.Context, fields *ModifiedCraftingIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookModifiedCraftingIndex != nil {
			return CNHookModifiedCraftingIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringModifiedCraftingIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ModifiedCraftingIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ModifiedCraftingIndex
/* ModifiedCraftingIndex Returns the parent index for Modified Crafting. */
// Path: /data/wow/modified-crafting/index
var ModifiedCraftingIndex = bridgeModifiedCraftingIndex


// ==============================================================================================
// API: ModifiedCraftingCategoryIndex
// ==============================================================================================

type ModifiedCraftingCategoryIndexFields struct {
	Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookModifiedCraftingCategoryIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookModifiedCraftingCategoryIndex func(context.Context, *ModifiedCraftingCategoryIndexFields) (any, error)

// StringModifiedCraftingCategoryIndex executes the request and returns the raw response body string.
func StringModifiedCraftingCategoryIndex(ctx context.Context, fields *ModifiedCraftingCategoryIndexFields) (string, error) {
	if fields == nil {
		fields = &ModifiedCraftingCategoryIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ModifiedCraftingCategoryIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/modified-crafting/category/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeModifiedCraftingCategoryIndex routes the request to either CN or Global logic based on input.
func bridgeModifiedCraftingCategoryIndex(ctx context.Context, fields *ModifiedCraftingCategoryIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookModifiedCraftingCategoryIndex != nil {
			return CNHookModifiedCraftingCategoryIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringModifiedCraftingCategoryIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ModifiedCraftingCategoryIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ModifiedCraftingCategoryIndex
/* ModifiedCraftingCategoryIndex Returns the index of Modified Crafting categories. */
// Path: /data/wow/modified-crafting/category/index
var ModifiedCraftingCategoryIndex = bridgeModifiedCraftingCategoryIndex


// ==============================================================================================
// API: ModifiedCraftingCategory
// ==============================================================================================

type ModifiedCraftingCategoryFields struct {
	CategoryId int `uri:"categoryId" binding:"required"` // The ID of the Modified Crafting category.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookModifiedCraftingCategory allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookModifiedCraftingCategory func(context.Context, *ModifiedCraftingCategoryFields) (any, error)

// StringModifiedCraftingCategory executes the request and returns the raw response body string.
func StringModifiedCraftingCategory(ctx context.Context, fields *ModifiedCraftingCategoryFields) (string, error) {
	if fields == nil {
		fields = &ModifiedCraftingCategoryFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ModifiedCraftingCategory")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/modified-crafting/category/{categoryId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.CategoryId == 0 {
		fields.CategoryId = 1
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"categoryId": fields.CategoryId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeModifiedCraftingCategory routes the request to either CN or Global logic based on input.
func bridgeModifiedCraftingCategory(ctx context.Context, fields *ModifiedCraftingCategoryFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookModifiedCraftingCategory != nil {
			return CNHookModifiedCraftingCategory(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringModifiedCraftingCategory(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ModifiedCraftingCategoryModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ModifiedCraftingCategory
/* ModifiedCraftingCategory Returns a Modified Crafting category by ID. */
// Path: /data/wow/modified-crafting/category/{categoryId}
var ModifiedCraftingCategory = bridgeModifiedCraftingCategory


// ==============================================================================================
// API: ModifiedCraftingReagentSlotTypeIndex
// ==============================================================================================

type ModifiedCraftingReagentSlotTypeIndexFields struct {
	Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookModifiedCraftingReagentSlotTypeIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookModifiedCraftingReagentSlotTypeIndex func(context.Context, *ModifiedCraftingReagentSlotTypeIndexFields) (any, error)

// StringModifiedCraftingReagentSlotTypeIndex executes the request and returns the raw response body string.
func StringModifiedCraftingReagentSlotTypeIndex(ctx context.Context, fields *ModifiedCraftingReagentSlotTypeIndexFields) (string, error) {
	if fields == nil {
		fields = &ModifiedCraftingReagentSlotTypeIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ModifiedCraftingReagentSlotTypeIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/modified-crafting/reagent-slot-type/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeModifiedCraftingReagentSlotTypeIndex routes the request to either CN or Global logic based on input.
func bridgeModifiedCraftingReagentSlotTypeIndex(ctx context.Context, fields *ModifiedCraftingReagentSlotTypeIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookModifiedCraftingReagentSlotTypeIndex != nil {
			return CNHookModifiedCraftingReagentSlotTypeIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringModifiedCraftingReagentSlotTypeIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ModifiedCraftingReagentSlotTypeIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ModifiedCraftingReagentSlotTypeIndex
/* ModifiedCraftingReagentSlotTypeIndex Returns the index of Modified Crafting reagent slot types. */
// Path: /data/wow/modified-crafting/reagent-slot-type/index
var ModifiedCraftingReagentSlotTypeIndex = bridgeModifiedCraftingReagentSlotTypeIndex


// ==============================================================================================
// API: ModifiedCraftingReagentSlotType
// ==============================================================================================

type ModifiedCraftingReagentSlotTypeFields struct {
	SlotTypeId int `uri:"slotTypeId" binding:"required"` // The ID of the Modified Crafting reagent slot type.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookModifiedCraftingReagentSlotType allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookModifiedCraftingReagentSlotType func(context.Context, *ModifiedCraftingReagentSlotTypeFields) (any, error)

// StringModifiedCraftingReagentSlotType executes the request and returns the raw response body string.
func StringModifiedCraftingReagentSlotType(ctx context.Context, fields *ModifiedCraftingReagentSlotTypeFields) (string, error) {
	if fields == nil {
		fields = &ModifiedCraftingReagentSlotTypeFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ModifiedCraftingReagentSlotType")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/modified-crafting/reagent-slot-type/{slotTypeId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.SlotTypeId == 0 {
		fields.SlotTypeId = 16
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"slotTypeId": fields.SlotTypeId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeModifiedCraftingReagentSlotType routes the request to either CN or Global logic based on input.
func bridgeModifiedCraftingReagentSlotType(ctx context.Context, fields *ModifiedCraftingReagentSlotTypeFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookModifiedCraftingReagentSlotType != nil {
			return CNHookModifiedCraftingReagentSlotType(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringModifiedCraftingReagentSlotType(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ModifiedCraftingReagentSlotTypeModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ModifiedCraftingReagentSlotType
/* ModifiedCraftingReagentSlotType Returns a Modified Crafting reagent slot type by ID. */
// Path: /data/wow/modified-crafting/reagent-slot-type/{slotTypeId}
var ModifiedCraftingReagentSlotType = bridgeModifiedCraftingReagentSlotType

