package wowRetail_Mount
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetMountsIndexResponse is the unified BNet representation for MountsIndex.
type BNetMountsIndexResponse struct{}

// MountsIndexResponse represents the raw CN API response for MountsIndex.
type MountsIndexResponse BNetMountsIndexResponse

// ToBNet converts the CN response to the unified BNetMountsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *MountsIndexResponse) ToBNet() any {
	return r 
}

