package wow_CharacterAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterAppearanceSummaryResponse is the unified BNet representation for CharacterAppearanceSummary.
type BNetCharacterAppearanceSummaryResponse struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	PlayableRace struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"playable_race"`
	PlayableClass struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"playable_class"`
	ActiveSpec struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"active_spec"`
	Gender struct {
		Type string `json:"type"`
		Name string `json:"name"`
	} `json:"gender"`
	Faction struct {
		Type string `json:"type"`
		Name string `json:"name"`
	} `json:"faction"`
	Items []struct {
		Id   int `json:"id"`
		Slot struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"slot"`
		Enchant                  int `json:"enchant"`
		ItemAppearanceModifierId int `json:"item_appearance_modifier_id"`
		InternalSlotId           int `json:"internal_slot_id"`
		Subclass                 int `json:"subclass"`
	} `json:"items"`
	Customizations []struct {
		Option struct {
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"option"`
		Choice struct {
			Name         *string `json:"name,omitempty"`
			Id           int     `json:"id"`
			DisplayOrder int     `json:"display_order"`
		} `json:"choice"`
	} `json:"customizations"`
}

// CharacterAppearanceSummaryResponse represents the raw CN API response for CharacterAppearanceSummary.
type CharacterAppearanceSummaryResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterAppearanceSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterAppearanceSummaryResponse) ToBNet() any {
	return nil
}
