package wowRetail_AzeriteEssence
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAzeriteEssencesIndexResponse is the unified BNet representation for AzeriteEssencesIndex.
type BNetAzeriteEssencesIndexResponse struct{}

// AzeriteEssencesIndexResponse represents the raw CN API response for AzeriteEssencesIndex.
type AzeriteEssencesIndexResponse BNetAzeriteEssencesIndexResponse

// ToBNet converts the CN response to the unified BNetAzeriteEssencesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AzeriteEssencesIndexResponse) ToBNet() any {
	return r 
}

