package wowRetail_AzeriteEssence
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAzeriteEssenceMediaResponse is the unified BNet representation for AzeriteEssenceMedia.
type BNetAzeriteEssenceMediaResponse struct{}

// AzeriteEssenceMediaResponse represents the raw CN API response for AzeriteEssenceMedia.
type AzeriteEssenceMediaResponse BNetAzeriteEssenceMediaResponse

// ToBNet converts the CN response to the unified BNetAzeriteEssenceMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AzeriteEssenceMediaResponse) ToBNet() any {
	return r 
}

