package wowRetail_AzeriteEssence
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAzeriteEssenceResponse is the unified BNet representation for AzeriteEssence.
type BNetAzeriteEssenceResponse struct{}

// AzeriteEssenceResponse represents the raw CN API response for AzeriteEssence.
type AzeriteEssenceResponse BNetAzeriteEssenceResponse

// ToBNet converts the CN response to the unified BNetAzeriteEssenceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AzeriteEssenceResponse) ToBNet() any {
	return r 
}

