package wow_CharacterQuests

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/jtacoma/uritemplates"
)

//==============================================================================================

type CharacterQuestsFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterQuestsField(input *CharacterQuestsFields) *CharacterQuestsFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/quests",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterQuests(ctx context.Context, fields *CharacterQuestsFields) (string, error) {
	if fields == nil {
		fields = &CharacterQuestsFields{}
	}

	func(input *CharacterQuestsFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/quests",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterQuests(ctx context.Context, fields *CharacterQuestsFields) (any, error) {

	obj, err := cnStringCharacterQuests(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                      `json:"code"`
		Message string                   `json:"message"`
		Data    *CharacterQuestsResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterQuests(ctx context.Context, fields *CharacterQuestsFields) (string, error) {
	return "", ApiError.ErrorNotSupported
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func bridgeCharacterQuests(ctx context.Context, fields *CharacterQuestsFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterQuests(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterQuestsResponse).ToBNet(), nil
	}
	obj, err := StringCharacterQuests(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterQuestsResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterQuests Returns a character's active quests as well as a link to the character's completed quests.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/quests
var CharacterQuests = bridgeCharacterQuests

//==============================================================================================

type CharacterCompletedQuestsFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterCompletedQuestsField(input *CharacterCompletedQuestsFields) *CharacterCompletedQuestsFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/quests/completed",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterCompletedQuests(ctx context.Context, fields *CharacterCompletedQuestsFields) (string, error) {
	if fields == nil {
		fields = &CharacterCompletedQuestsFields{}
	}

	func(input *CharacterCompletedQuestsFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/quests/completed",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterCompletedQuests(ctx context.Context, fields *CharacterCompletedQuestsFields) (any, error) {

	obj, err := cnStringCharacterCompletedQuests(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                               `json:"code"`
		Message string                            `json:"message"`
		Data    *CharacterCompletedQuestsResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterCompletedQuests(ctx context.Context, fields *CharacterCompletedQuestsFields) (string, error) {
	return "", ApiError.ErrorNotSupported
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func bridgeCharacterCompletedQuests(ctx context.Context, fields *CharacterCompletedQuestsFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterCompletedQuests(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterCompletedQuestsResponse).ToBNet(), nil
	}
	obj, err := StringCharacterCompletedQuests(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterCompletedQuestsResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterCompletedQuests Returns a list of quests that a character has completed.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/quests/completed
var CharacterCompletedQuests = bridgeCharacterCompletedQuests
