package wowRetail_AuctionHouse
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetAuctionsResponse is the unified BNet representation for Auctions.
type BNetAuctionsResponse struct{}

// AuctionsResponse represents the raw CN API response for Auctions.
type AuctionsResponse BNetAuctionsResponse

// ToBNet converts the CN response to the unified BNetAuctionsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AuctionsResponse) ToBNet() any {
	return r 
}

