package wowRetail_AuctionHouse
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetCommoditiesResponse is the unified BNet representation for Commodities.
type BNetCommoditiesResponse struct{}

// CommoditiesResponse represents the raw CN API response for Commodities.
type CommoditiesResponse BNetCommoditiesResponse

// ToBNet converts the CN response to the unified BNetCommoditiesResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CommoditiesResponse) ToBNet() any {
	return r 
}

