package wowClassic_PvPSeason
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPvPRegionalSeasonIndexResponse is the unified BNet representation for PvPRegionalSeasonIndex.
type BNetPvPRegionalSeasonIndexResponse struct{}

// PvPRegionalSeasonIndexResponse represents the raw CN API response for PvPRegionalSeasonIndex.
type PvPRegionalSeasonIndexResponse BNetPvPRegionalSeasonIndexResponse

// ToBNet converts the CN response to the unified BNetPvPRegionalSeasonIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PvPRegionalSeasonIndexResponse) ToBNet() any {
	return r 
}

