package wowClassic_PvPSeason
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type PvPSeasonsIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPSeasonsIndexField(input *PvPSeasonsIndexFields) *PvPSeasonsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-season/index",
//			CnRegion:false ,
//}
//return input
//}


//PvPSeasonsIndex Returns an index of PvP seasons.
//
//@see: /data/wow/pvp-season/index
func StringPvPSeasonsIndex(ctx context.Context, fields *PvPSeasonsIndexFields)(string,error){
	if fields == nil {
		fields = &PvPSeasonsIndexFields{}
	}

	func(input *PvPSeasonsIndexFields) {
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-season/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPSeasonsIndex(ctx context.Context, fields *PvPSeasonsIndexFields)(any,error){

obj, err := StringPvPSeasonsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPSeasonsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPSeasonsIndex = CNPvPSeasonsIndex
/*func BNetPvPSeasonsIndex(ctx context.Context, fields *PvPSeasonsIndexFields)(any,error){

obj ,err := CNPvPSeasonsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPSeasonsIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPSeasonFields struct{
	PvpSeasonId int//The ID of the PvP season.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPSeasonField(input *PvPSeasonFields) *PvPSeasonFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-season/{pvpSeasonId}",
//			CnRegion:false ,
//}
//return input
//}


//PvPSeason Returns a PvP season by ID.
//
//@see: /data/wow/pvp-season/{pvpSeasonId}
func StringPvPSeason(ctx context.Context, fields *PvPSeasonFields)(string,error){
	if fields == nil {
		fields = &PvPSeasonFields{}
	}

	func(input *PvPSeasonFields) {
	
if input.PvpSeasonId==0{
input.PvpSeasonId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-season/{pvpSeasonId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpSeasonId", strconv.Itoa(fields.PvpSeasonId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPSeason(ctx context.Context, fields *PvPSeasonFields)(any,error){

obj, err := StringPvPSeason(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPSeasonResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPSeason = CNPvPSeason
/*func BNetPvPSeason(ctx context.Context, fields *PvPSeasonFields)(any,error){

obj ,err := CNPvPSeason(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPSeasonResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPRegionIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPRegionIndexField(input *PvPRegionIndexFields) *PvPRegionIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/index",
//			CnRegion:false ,
//}
//return input
//}


//PvPRegionIndex Returns an index of PvP Regions.
//
//@see: /data/wow/pvp-region/index
func StringPvPRegionIndex(ctx context.Context, fields *PvPRegionIndexFields)(string,error){
	if fields == nil {
		fields = &PvPRegionIndexFields{}
	}

	func(input *PvPRegionIndexFields) {
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPRegionIndex(ctx context.Context, fields *PvPRegionIndexFields)(any,error){

obj, err := StringPvPRegionIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPRegionIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPRegionIndex = CNPvPRegionIndex
/*func BNetPvPRegionIndex(ctx context.Context, fields *PvPRegionIndexFields)(any,error){

obj ,err := CNPvPRegionIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPRegionIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPRegionalSeasonIndexFields struct{
	PvpRegionId int//The ID of the PvP region.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPRegionalSeasonIndexField(input *PvPRegionalSeasonIndexFields) *PvPRegionalSeasonIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/index",
//			CnRegion:false ,
//}
//return input
//}


//PvPRegionalSeasonIndex Returns an index of PvP Seasons in a PvP region.
//
//@see: /data/wow/pvp-region/{pvpRegionId}/pvp-season/index
func StringPvPRegionalSeasonIndex(ctx context.Context, fields *PvPRegionalSeasonIndexFields)(string,error){
	if fields == nil {
		fields = &PvPRegionalSeasonIndexFields{}
	}

	func(input *PvPRegionalSeasonIndexFields) {
	
if input.PvpRegionId==0{
input.PvpRegionId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpRegionId", strconv.Itoa(fields.PvpRegionId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPRegionalSeasonIndex(ctx context.Context, fields *PvPRegionalSeasonIndexFields)(any,error){

obj, err := StringPvPRegionalSeasonIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPRegionalSeasonIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPRegionalSeasonIndex = CNPvPRegionalSeasonIndex
/*func BNetPvPRegionalSeasonIndex(ctx context.Context, fields *PvPRegionalSeasonIndexFields)(any,error){

obj ,err := CNPvPRegionalSeasonIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPRegionalSeasonIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPRegionalSeasonFields struct{
	PvpRegionId int//The ID of the PvP region.
	PvpSeasonId int//The ID of the PvP season.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPRegionalSeasonField(input *PvPRegionalSeasonFields) *PvPRegionalSeasonFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}",
//			CnRegion:false ,
//}
//return input
//}


//PvPRegionalSeason Returns a PvP season by region ID and season ID.
//
//@see: /data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}
func StringPvPRegionalSeason(ctx context.Context, fields *PvPRegionalSeasonFields)(string,error){
	if fields == nil {
		fields = &PvPRegionalSeasonFields{}
	}

	func(input *PvPRegionalSeasonFields) {
	
if input.PvpRegionId==0{
input.PvpRegionId = 1
}
	
	
if input.PvpSeasonId==0{
input.PvpSeasonId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpRegionId", strconv.Itoa(fields.PvpRegionId))
	q.Add("pvpSeasonId", strconv.Itoa(fields.PvpSeasonId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPRegionalSeason(ctx context.Context, fields *PvPRegionalSeasonFields)(any,error){

obj, err := StringPvPRegionalSeason(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPRegionalSeasonResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPRegionalSeason = CNPvPRegionalSeason
/*func BNetPvPRegionalSeason(ctx context.Context, fields *PvPRegionalSeasonFields)(any,error){

obj ,err := CNPvPRegionalSeason(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPRegionalSeasonResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPLeaderboardsIndexFields struct{
	PvpRegionId int//The ID of the PvP region.
	PvpSeasonId int//The ID of the PvP season.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPLeaderboardsIndexField(input *PvPLeaderboardsIndexFields) *PvPLeaderboardsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/index",
//			CnRegion:false ,
//}
//return input
//}


//PvPLeaderboardsIndex Returns an index of PvP leaderboards for a PvP season in a given PvP region.
//
//@see: /data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/index
func StringPvPLeaderboardsIndex(ctx context.Context, fields *PvPLeaderboardsIndexFields)(string,error){
	if fields == nil {
		fields = &PvPLeaderboardsIndexFields{}
	}

	func(input *PvPLeaderboardsIndexFields) {
	
if input.PvpRegionId==0{
input.PvpRegionId = 1
}
	
	
if input.PvpSeasonId==0{
input.PvpSeasonId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpRegionId", strconv.Itoa(fields.PvpRegionId))
	q.Add("pvpSeasonId", strconv.Itoa(fields.PvpSeasonId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPLeaderboardsIndex(ctx context.Context, fields *PvPLeaderboardsIndexFields)(any,error){

obj, err := StringPvPLeaderboardsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPLeaderboardsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPLeaderboardsIndex = CNPvPLeaderboardsIndex
/*func BNetPvPLeaderboardsIndex(ctx context.Context, fields *PvPLeaderboardsIndexFields)(any,error){

obj ,err := CNPvPLeaderboardsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPLeaderboardsIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPLeaderboardFields struct{
	PvpRegionId int//The ID of the PvP region.
	PvpSeasonId int//The ID of the PvP season.
	PvpBracket string//The PvP bracket type.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPLeaderboardField(input *PvPLeaderboardFields) *PvPLeaderboardFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}",
//			CnRegion:false ,
//}
//return input
//}


//PvPLeaderboard Returns the PvP leaderboard of a specific PvP bracket for a PvP season in a given PvP region.
//
//@see: /data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}
func StringPvPLeaderboard(ctx context.Context, fields *PvPLeaderboardFields)(string,error){
	if fields == nil {
		fields = &PvPLeaderboardFields{}
	}

	func(input *PvPLeaderboardFields) {
	
if input.PvpRegionId==0{
input.PvpRegionId = 1
}
	
	
if input.PvpSeasonId==0{
input.PvpSeasonId = 1
}
	
	
if input.PvpBracket==""{
input.PvpBracket = "3v3"
}

	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpRegionId", strconv.Itoa(fields.PvpRegionId))
	q.Add("pvpSeasonId", strconv.Itoa(fields.PvpSeasonId))
	q.Add("pvpBracket", fields.PvpBracket)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPLeaderboard(ctx context.Context, fields *PvPLeaderboardFields)(any,error){

obj, err := StringPvPLeaderboard(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPLeaderboardResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPLeaderboard = CNPvPLeaderboard
/*func BNetPvPLeaderboard(ctx context.Context, fields *PvPLeaderboardFields)(any,error){

obj ,err := CNPvPLeaderboard(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPLeaderboardResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PvPRewardsIndexFields struct{
	PvpRegionId int//The ID of the PvP region.
	PvpSeasonId int//The ID of the PvP season.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PvPRewardsIndexField(input *PvPRewardsIndexFields) *PvPRewardsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-reward/index",
//			CnRegion:false ,
//}
//return input
//}


//PvPRewardsIndex Returns an index of PvP rewards for a PvP season in a given PvP region.
//
//@see: /data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-reward/index
func StringPvPRewardsIndex(ctx context.Context, fields *PvPRewardsIndexFields)(string,error){
	if fields == nil {
		fields = &PvPRewardsIndexFields{}
	}

	func(input *PvPRewardsIndexFields) {
	
if input.PvpRegionId==0{
input.PvpRegionId = 1
}
	
	
if input.PvpSeasonId==0{
input.PvpSeasonId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/pvp-region/{pvpRegionId}/pvp-season/{pvpSeasonId}/pvp-reward/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("pvpRegionId", strconv.Itoa(fields.PvpRegionId))
	q.Add("pvpSeasonId", strconv.Itoa(fields.PvpSeasonId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPvPRewardsIndex(ctx context.Context, fields *PvPRewardsIndexFields)(any,error){

obj, err := StringPvPRewardsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PvPRewardsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PvPRewardsIndex = CNPvPRewardsIndex
/*func BNetPvPRewardsIndex(ctx context.Context, fields *PvPRewardsIndexFields)(any,error){

obj ,err := CNPvPRewardsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PvPRewardsIndexResponse).ToBNet(),nil
}*/


