package wowRetail_HousingDecor
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetDecorIndexResponse is the unified BNet representation for DecorIndex.
type BNetDecorIndexResponse struct{}

// DecorIndexResponse represents the raw CN API response for DecorIndex.
type DecorIndexResponse BNetDecorIndexResponse

// ToBNet converts the CN response to the unified BNetDecorIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *DecorIndexResponse) ToBNet() any {
	return r 
}

