package wowRetail_HousingDecor
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetFixtureIndexResponse is the unified BNet representation for FixtureIndex.
type BNetFixtureIndexResponse struct{}

// FixtureIndexResponse represents the raw CN API response for FixtureIndex.
type FixtureIndexResponse BNetFixtureIndexResponse

// ToBNet converts the CN response to the unified BNetFixtureIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *FixtureIndexResponse) ToBNet() any {
	return r 
}

