package wowRetail_HousingDecor
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetFixtureSearchResponse is the unified BNet representation for FixtureSearch.
type BNetFixtureSearchResponse struct{}

// FixtureSearchResponse represents the raw CN API response for FixtureSearch.
type FixtureSearchResponse BNetFixtureSearchResponse

// ToBNet converts the CN response to the unified BNetFixtureSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *FixtureSearchResponse) ToBNet() any {
	return r 
}

