package wowRetail_HousingDecor
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetRoomSearchResponse is the unified BNet representation for RoomSearch.
type BNetRoomSearchResponse struct{}

// RoomSearchResponse represents the raw CN API response for RoomSearch.
type RoomSearchResponse BNetRoomSearchResponse

// ToBNet converts the CN response to the unified BNetRoomSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *RoomSearchResponse) ToBNet() any {
	return r 
}

