package wowClassic_Realm
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetRealmSearchResponse is the unified BNet representation for RealmSearch.
type BNetRealmSearchResponse struct{}

// RealmSearchResponse represents the raw CN API response for RealmSearch.
type RealmSearchResponse BNetRealmSearchResponse

// ToBNet converts the CN response to the unified BNetRealmSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *RealmSearchResponse) ToBNet() any {
	return r 
}

