package D3_D3Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: GetItem
// ==============================================================================================

type GetItemFields struct {
	ItemSlugAndId string `uri:"itemSlugAndId" binding:"required"` // The slug and ID of the item to retrieve.
		Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookGetItem allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookGetItem func(context.Context, *GetItemFields) (any, error)

// StringGetItem executes the request and returns the raw response body string.
func StringGetItem(ctx context.Context, fields *GetItemFields) (string, error) {
	if fields == nil {
		fields = &GetItemFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("GetItem")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/d3/data/item/{itemSlugAndId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.ItemSlugAndId == "" {
		fields.ItemSlugAndId = "corrupted-ashbringer-Unique_Sword_2H_104_x1"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"itemSlugAndId": fields.ItemSlugAndId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeGetItem routes the request to either CN or Global logic based on input.
func bridgeGetItem(ctx context.Context, fields *GetItemFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookGetItem != nil {
			return CNHookGetItem(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringGetItem(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &GetItemModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GetItem
/* GetItem Returns a single item by item slug and ID. */
// Path: /d3/data/item/{itemSlugAndId}
var GetItem = bridgeGetItem

