package wowClassic_GuildCrest
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type GuildCrestComponentsIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func GuildCrestComponentsIndexField(input *GuildCrestComponentsIndexFields) *GuildCrestComponentsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/guild-crest/index",
//			CnRegion:false ,
//}
//return input
//}


//GuildCrestComponentsIndex Returns an index of guild crest media.
//
//@see: /data/wow/guild-crest/index
func StringGuildCrestComponentsIndex(ctx context.Context, fields *GuildCrestComponentsIndexFields)(string,error){
	if fields == nil {
		fields = &GuildCrestComponentsIndexFields{}
	}

	func(input *GuildCrestComponentsIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/guild-crest/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildCrestComponentsIndex(ctx context.Context, fields *GuildCrestComponentsIndexFields)(any,error){

obj, err := StringGuildCrestComponentsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&GuildCrestComponentsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var GuildCrestComponentsIndex = CNGuildCrestComponentsIndex
/*func BNetGuildCrestComponentsIndex(ctx context.Context, fields *GuildCrestComponentsIndexFields)(any,error){

obj ,err := CNGuildCrestComponentsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*GuildCrestComponentsIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type GuildCrestBorderMediaFields struct{
	BorderId int//The ID of the guild crest border.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func GuildCrestBorderMediaField(input *GuildCrestBorderMediaFields) *GuildCrestBorderMediaFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/media/guild-crest/border/{borderId}",
//			CnRegion:false ,
//}
//return input
//}


//GuildCrestBorderMedia Returns media for a guild crest border by ID.
//
//@see: /data/wow/media/guild-crest/border/{borderId}
func StringGuildCrestBorderMedia(ctx context.Context, fields *GuildCrestBorderMediaFields)(string,error){
	if fields == nil {
		fields = &GuildCrestBorderMediaFields{}
	}

	func(input *GuildCrestBorderMediaFields) {
	
if input.BorderId==0{
input.BorderId = 0
}
	
	
if input.Namespace==""{
input.Namespace = "static-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/media/guild-crest/border/{borderId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("borderId", strconv.Itoa(fields.BorderId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildCrestBorderMedia(ctx context.Context, fields *GuildCrestBorderMediaFields)(any,error){

obj, err := StringGuildCrestBorderMedia(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&GuildCrestBorderMediaResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var GuildCrestBorderMedia = CNGuildCrestBorderMedia
/*func BNetGuildCrestBorderMedia(ctx context.Context, fields *GuildCrestBorderMediaFields)(any,error){

obj ,err := CNGuildCrestBorderMedia(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*GuildCrestBorderMediaResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type GuildCrestEmblemMediaFields struct{
	EmblemId int//The ID of the guild crest emblem.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func GuildCrestEmblemMediaField(input *GuildCrestEmblemMediaFields) *GuildCrestEmblemMediaFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/media/guild-crest/emblem/{emblemId}",
//			CnRegion:false ,
//}
//return input
//}


//GuildCrestEmblemMedia Returns media for a guild crest emblem by ID.
//
//@see: /data/wow/media/guild-crest/emblem/{emblemId}
func StringGuildCrestEmblemMedia(ctx context.Context, fields *GuildCrestEmblemMediaFields)(string,error){
	if fields == nil {
		fields = &GuildCrestEmblemMediaFields{}
	}

	func(input *GuildCrestEmblemMediaFields) {
	
if input.EmblemId==0{
input.EmblemId = 0
}
	
	
if input.Namespace==""{
input.Namespace = "static-classic-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/media/guild-crest/emblem/{emblemId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("emblemId", strconv.Itoa(fields.EmblemId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildCrestEmblemMedia(ctx context.Context, fields *GuildCrestEmblemMediaFields)(any,error){

obj, err := StringGuildCrestEmblemMedia(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&GuildCrestEmblemMediaResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var GuildCrestEmblemMedia = CNGuildCrestEmblemMedia
/*func BNetGuildCrestEmblemMedia(ctx context.Context, fields *GuildCrestEmblemMediaFields)(any,error){

obj ,err := CNGuildCrestEmblemMedia(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*GuildCrestEmblemMediaResponse).ToBNet(),nil
}*/


