package wowClassic_GuildCrest
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetGuildCrestBorderMediaResponse is the unified BNet representation for GuildCrestBorderMedia.
type BNetGuildCrestBorderMediaResponse struct{}

// GuildCrestBorderMediaResponse represents the raw CN API response for GuildCrestBorderMedia.
type GuildCrestBorderMediaResponse BNetGuildCrestBorderMediaResponse

// ToBNet converts the CN response to the unified BNetGuildCrestBorderMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *GuildCrestBorderMediaResponse) ToBNet() any {
	return r 
}

