package StarCraftII_StarCraftIILeague

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: GetLeagueData
// ==============================================================================================

type GetLeagueDataFields struct {
	SeasonId string `uri:"seasonId" binding:"required"` // The season ID of the data to retrieve.
		QueueId string `uri:"queueId" binding:"required"` // The queue ID of the data to retrieve.
		TeamType string `uri:"teamType" binding:"required"` // The team type of the data to retrieve.
		LeagueId string `uri:"leagueId" binding:"required"` // The league ID of the data to retrieve.
		Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookGetLeagueData allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookGetLeagueData func(context.Context, *GetLeagueDataFields) (any, error)

// StringGetLeagueData executes the request and returns the raw response body string.
func StringGetLeagueData(ctx context.Context, fields *GetLeagueDataFields) (string, error) {
	if fields == nil {
		fields = &GetLeagueDataFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("GetLeagueData")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/sc2/league/{seasonId}/{queueId}/{teamType}/{leagueId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.SeasonId == "" {
		fields.SeasonId = "37"
	}
	
	
	if fields.QueueId == "" {
		fields.QueueId = "201"
	}
	
	
	if fields.TeamType == "" {
		fields.TeamType = "0"
	}
	
	
	if fields.LeagueId == "" {
		fields.LeagueId = "6"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"seasonId": fields.SeasonId,
    		"queueId": fields.QueueId,
    		"teamType": fields.TeamType,
    		"leagueId": fields.LeagueId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeGetLeagueData routes the request to either CN or Global logic based on input.
func bridgeGetLeagueData(ctx context.Context, fields *GetLeagueDataFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookGetLeagueData != nil {
			return CNHookGetLeagueData(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringGetLeagueData(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &GetLeagueDataModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GetLeagueData
/* GetLeagueData Returns data for the specified season, queue, team, and league.

**queueId**: the standard available queueIds are: `1`=WoL 1v1, `2`=WoL 2v2, `3`=WoL 3v3, `4`=WoL 4v4, `101`=HotS 1v1, `102`=HotS 2v2, `103`=HotS 3v3, `104`=HotS 4v4, `201`=LotV 1v1, `202`=LotV 2v2, `203`=LotV 3v3, `204`=LotV 4v4, `206`=LotV Archon. Note that other available queues may not be listed here.

**teamType**: there are two available teamTypes: `0`=arranged, `1`=random.

**leagueId**: available leagueIds are: `0`=Bronze, `1`=Silver, `2`=Gold, `3`=Platinum, `4`=Diamond, `5`=Master, `6`=Grandmaster. */
// Path: /data/sc2/league/{seasonId}/{queueId}/{teamType}/{leagueId}
var GetLeagueData = bridgeGetLeagueData

