package wowRetail

import (
	"github.com/jinzhu/copier"
)

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountProfileSummaryResponse is the unified BNet representation for AccountProfileSummary.
type BNetAccountProfileSummaryResponse struct {
	/*	Links  Links  `json:"_links"`*/
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Gender struct {
		Type string `json:"type"`
		Name string `json:"name"`
	} `json:"gender"`
	Faction struct {
		Type string `json:"type"`
		Name string `json:"name"`
	} `json:"faction"`
	Race struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"race"`
	CharacterClass struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"character_class"`
	ActiveSpec struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"active_spec"`
	Realm struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
		Slug string `json:"slug"`
	} `json:"realm"`
	Guild struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
		Faction struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"faction"`
	} `json:"guild"`
	Level             int `json:"level"`
	Experience        int `json:"experience"`
	AchievementPoints int `json:"achievement_points"`
	Achievements      struct {
		Href string `json:"href"`
	} `json:"achievements"`
	Titles struct {
		Href string `json:"href"`
	} `json:"titles"`
	PvpSummary struct {
		Href string `json:"href"`
	} `json:"pvp_summary"`
	Encounters struct {
		Href string `json:"href"`
	} `json:"encounters"`
	Media struct {
		Href string `json:"href"`
	} `json:"media"`
	LastLoginTimestamp int64 `json:"last_login_timestamp"`
	AverageItemLevel   int   `json:"average_item_level"`
	EquippedItemLevel  int   `json:"equipped_item_level"`
	Specializations    struct {
		Href string `json:"href"`
	} `json:"specializations"`
	Statistics struct {
		Href string `json:"href"`
	} `json:"statistics"`
	MythicKeystoneProfile struct {
		Href string `json:"href"`
	} `json:"mythic_keystone_profile"`
	Equipment struct {
		Href string `json:"href"`
	} `json:"equipment"`
	Appearance struct {
		Href string `json:"href"`
	} `json:"appearance"`
	Collections struct {
		Href string `json:"href"`
	} `json:"collections"`
	ActiveTitle struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name          string `json:"name"`
		Id            int    `json:"id"`
		DisplayString string `json:"display_string"`
	} `json:"active_title"`
	Reputations struct {
		Href string `json:"href"`
	} `json:"reputations"`
	Quests struct {
		Href string `json:"href"`
	} `json:"quests"`
	AchievementsStatistics struct {
		Href string `json:"href"`
	} `json:"achievements_statistics"`
	Professions struct {
		Href string `json:"href"`
	} `json:"professions"`
	CovenantProgress struct {
		ChosenCovenant struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"chosen_covenant"`
		RenownLevel int `json:"renown_level"`
		Soulbinds   struct {
			Href string `json:"href"`
		} `json:"soulbinds"`
	} `json:"covenant_progress"`
	IsRemix bool `json:"is_remix"`
	Houses  []struct {
		Href string `json:"href"`
	} `json:"houses"`
	NameSearch string `json:"name_search"`
}

// AccountProfileSummaryResponse represents the raw CN API response for AccountProfileSummary.
type AccountProfileSummaryResponse struct {
	CharacterSummary struct {
		Name   string `json:"name"`
		Gender struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"gender"`
		Faction struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"faction"`
		Race struct {
			Name string `json:"name"`
		} `json:"race"`
		CharacterClass struct {
			Id   int    `json:"id"`
			Name string `json:"name"`
		} `json:"character_class"`
		ActiveSpec struct {
			Name string `json:"name"`
		} `json:"active_spec"`
		Realm struct {
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
		Guild struct {
			Name  string `json:"name"`
			Realm struct {
				Name string `json:"name"`
				Slug string `json:"slug"`
			} `json:"realm"`
			Faction struct {
				Type string `json:"type"`
				Name string `json:"name"`
			} `json:"faction"`
		} `json:"guild"`
		Level              int   `json:"level"`
		Experience         int   `json:"experience"`
		AchievementPoints  int   `json:"achievement_points"`
		LastLoginTimestamp int64 `json:"last_login_timestamp"`
		AverageItemLevel   int   `json:"average_item_level"`
		EquippedItemLevel  int   `json:"equipped_item_level"`
		ActiveTitle        struct {
			Name          string `json:"name"`
			DisplayString string `json:"display_string"`
		} `json:"active_title"`
		CovenantProgress struct {
			ChosenCovenant struct {
				Name string `json:"name"`
			} `json:"chosen_covenant"`
			RenownLevel int `json:"renown_level"`
			Soulbinds   struct {
			} `json:"soulbinds"`
		} `json:"covenant_progress"`
		NameSearch string `json:"name_search"`
	} `json:"character_summary"`
	List                    []string `json:"list"`
	Token                   string   `json:"token"`
	IsSelf                  bool     `json:"is_self"`
	Allow                   bool     `json:"allow"`
	EncountersJson          string   `json:"encounters_json"`
	AchievementCategoryJson string   `json:"achievement_category_json"`
	CharacterMedia          struct {
		Assets []struct {
			Key   string `json:"key"`
			Value string `json:"value"`
		} `json:"assets"`
	} `json:"character_media"`
}

// ToBNet converts the CN response to the unified BNetAccountProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AccountProfileSummaryResponse) ToBNet() any {
	m := BNetAccountProfileSummaryResponse{}
	m.Name = r.CharacterSummary.Name

	copier.Copy(&m, &r.CharacterSummary)

	return m
}
