package wowRetail
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance


// BNetAccountToysCollectionSummaryResponse is the unified BNet representation for AccountToysCollectionSummary.
type BNetAccountToysCollectionSummaryResponse struct{}

// AccountToysCollectionSummaryResponse represents the raw CN API response for AccountToysCollectionSummary.
type AccountToysCollectionSummaryResponse struct{}

// ToBNet converts the CN response to the unified BNetAccountToysCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *AccountToysCollectionSummaryResponse) ToBNet() any {
	return nil
}

