package wowRetail
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance


// BNetCharacterMythicKeystoneSeasonDetailsResponse is the unified BNet representation for CharacterMythicKeystoneSeasonDetails.
type BNetCharacterMythicKeystoneSeasonDetailsResponse struct{}

// CharacterMythicKeystoneSeasonDetailsResponse represents the raw CN API response for CharacterMythicKeystoneSeasonDetails.
type CharacterMythicKeystoneSeasonDetailsResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterMythicKeystoneSeasonDetailsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterMythicKeystoneSeasonDetailsResponse) ToBNet() any {
	return nil
}

