package wowRetail

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"context"
	"encoding/json"
)

//CharacterCollectionsIndex Returns an index of collection types for a character.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections

func StringCharacterCollectionsIndex(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		//panic("CN API is not supported for this endpoint")
		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)*/

	return "", ApiError.ErrorNotSupported
}

func CNCharacterCollectionsIndex(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterCollectionsIndex(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterCollectionsIndexResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterCollectionsIndex(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterCollectionsIndex(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterCollectionsIndexResponse).ToBNet(), nil
}

//CharacterDecorCollectionSummary Returns a summary of the housing decor collection a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/decor

func StringCharacterDecorCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		//panic("CN API is not supported for this endpoint")
		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)*/

	return "", ApiError.ErrorNotSupported
}

func CNCharacterDecorCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterDecorCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterDecorCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterDecorCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterDecorCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterDecorCollectionSummaryResponse).ToBNet(), nil
}

//CharacterHeirloomsCollectionSummary Returns a summary of the heirlooms a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/heirlooms

func StringCharacterHeirloomsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		panic("CN API is not supported for this endpoint")

		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)*/
	return "", ApiError.ErrorNotSupported
}

func CNCharacterHeirloomsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterHeirloomsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterHeirloomsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterHeirloomsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterHeirloomsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterHeirloomsCollectionSummaryResponse).ToBNet(), nil
}

//CharacterMountsCollectionSummary Returns a summary of the mounts a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/mounts

func StringCharacterMountsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {

	token := internal.TryToGetToken(realmSlug, characterName)

	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "mounts", "token", token)
}

func CNCharacterMountsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterMountsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterMountsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterMountsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterMountsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterMountsCollectionSummaryResponse).ToBNet(), nil
}

//CharacterPetsCollectionSummary Returns a summary of the battle pets a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/pets

func StringCharacterPetsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {

	token := internal.TryToGetToken(realmSlug, characterName)

	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "pets", "token", token)
}

func CNCharacterPetsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterPetsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterPetsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterPetsCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterPetsCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterPetsCollectionSummaryResponse).ToBNet(), nil
}

//CharacterToysCollectionSummary Returns a summary of the toys a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/toys

func StringCharacterToysCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "toys", "token", token)*/

	return "", ApiError.ErrorNotSupported
}

func CNCharacterToysCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterToysCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterToysCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterToysCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterToysCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterToysCollectionSummaryResponse).ToBNet(), nil
}

//CharacterTransmogCollectionSummary Returns a summary of the transmog unlocks a character has obtained.
//@see: /profile/wow/character/{realmSlug}/{characterName}/collections/transmogs

func StringCharacterTransmogCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	//client := utils.NewRequest()
	//token := internal.TryToGetToken(realmSlug, characterName)
	//return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)

	return "", ApiError.ErrorNotSupported
}

func CNCharacterTransmogCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterTransmogCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterTransmogCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterTransmogCollectionSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterTransmogCollectionSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterTransmogCollectionSummaryResponse).ToBNet(), nil
}
