package wowRetail

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"context"
	"encoding/json"
	"fmt"
)

//CharacterMythicKeystoneProfileIndex Returns the Mythic Keystone profile index for a character.
//@see: /profile/wow/character/{realmSlug}/{characterName}/mythic-keystone-profile

func StringCharacterMythicKeystoneProfileIndex(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {

	token := internal.TryToGetToken(realmSlug, characterName)

	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func CNCharacterMythicKeystoneProfileIndex(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterMythicKeystoneProfileIndex(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterMythicKeystoneProfileIndexResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterMythicKeystoneProfileIndex(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {
	obj, err := CNCharacterMythicKeystoneProfileIndex(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	return obj.(*CharacterMythicKeystoneProfileIndexResponse).ToBNet(), nil
}

//CharacterMythicKeystoneSeasonDetails Returns the Mythic Keystone season details for a character.<br/><br/>Returns a <strong>404 Not Found</strong> for characters that have not yet completed a Mythic Keystone dungeon for the specified season.
//@see: /profile/wow/character/{realmSlug}/{characterName}/mythic-keystone-profile/season/{seasonId}

func StringCharacterMythicKeystoneSeasonDetails(ctx context.Context,
	realmSlug string, characterName string, seasonId string,
) (string, error) {

	token := internal.TryToGetToken(realmSlug, characterName)
	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "mythic_keystone_profile", "token", token)

	return "", fmt.Errorf("This method is in development and may not function as expected. so far it will just return the full mythic keystone profile")
}

func CNCharacterMythicKeystoneSeasonDetails(ctx context.Context,
	realmSlug string, characterName string, seasonId string,
) (any, error) {

	obj, err := StringCharacterMythicKeystoneSeasonDetails(ctx, realmSlug, characterName, seasonId)
	if err != nil {
		return nil, err
	}
	resp := &CharacterMythicKeystoneSeasonDetailsResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterMythicKeystoneSeasonDetails(ctx context.Context,
	realmSlug string, characterName string, seasonId string,
) (any, error) {

	obj, err := CNCharacterMythicKeystoneSeasonDetails(ctx, realmSlug, characterName, seasonId)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterMythicKeystoneSeasonDetailsResponse).ToBNet(), nil
}
