package wowRetail

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"context"
	"encoding/json"
	"fmt"
)

//CharacterAppearanceSummary Returns a summary of a character's appearance settings.
//@see: /profile/wow/character/{realmSlug}/{characterName}/appearance

func StringCharacterAppearanceSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*client := utils.NewRequest()
	token := internal.TryToGetToken(realmSlug, characterName)*/
	//panic("CN API is not supported for this endpoint")
	//return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
	return "", fmt.Errorf("CN API is not supported for this endpoint")
}

func CNCharacterAppearanceSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterAppearanceSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterAppearanceSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterAppearanceSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterAppearanceSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterAppearanceSummaryResponse).ToBNet(), nil
}
