package wowRetail
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance


// BNetCharacterQuestsResponse is the unified BNet representation for CharacterQuests.
type BNetCharacterQuestsResponse struct{}

// CharacterQuestsResponse represents the raw CN API response for CharacterQuests.
type CharacterQuestsResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterQuestsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterQuestsResponse) ToBNet() any {
	return nil
}

