package wowRetail

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"context"
	"encoding/json"
)

//CharacterEncountersSummary Returns a summary of a character's encounters.
//@see: /profile/wow/character/{realmSlug}/{characterName}/encounters

func StringCharacterEncountersSummary(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		panic("CN API is not supported for this endpoint")
		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)*/

	return "", ApiError.ErrorNotSupported
}

func CNCharacterEncountersSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterEncountersSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterEncountersSummaryResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterEncountersSummary(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterEncountersSummary(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterEncountersSummaryResponse).ToBNet(), nil
}

//CharacterDungeons Returns a summary of a character's completed dungeons.
//@see: /profile/wow/character/{realmSlug}/{characterName}/encounters/dungeons

func StringCharacterDungeons(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {
	/*	client := utils.NewRequest()
		token := internal.TryToGetToken(realmSlug, characterName)
		panic("CN API is not supported for this endpoint")
		return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)*/

	return "", ApiError.ErrorNotSupported
}

func CNCharacterDungeons(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterDungeons(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterDungeonsResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterDungeons(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterDungeons(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterDungeonsResponse).ToBNet(), nil
}

//CharacterRaids Returns a summary of a character's completed raids.
//@see: /profile/wow/character/{realmSlug}/{characterName}/encounters/raids

func StringCharacterRaids(ctx context.Context,
	realmSlug string, characterName string,
) (string, error) {

	token := internal.TryToGetToken(realmSlug, characterName)

	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func CNCharacterRaids(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := StringCharacterRaids(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}
	resp := &CharacterRaidsResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func BNetCharacterRaids(ctx context.Context,
	realmSlug string, characterName string,
) (any, error) {

	obj, err := CNCharacterRaids(ctx, realmSlug, characterName)
	if err != nil {
		return nil, err
	}

	return obj.(*CharacterRaidsResponse).ToBNet(), nil
}
