package wowRetail
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
)





 
//Guild Returns a single guild by its name and realm.
//@see: /data/wow/guild/{realmSlug}/{nameSlug}

func StringGuild(ctx context.Context,   ,
realmSlug string,nameSlug string,
)(string,error){
	client := utils.NewRequest()
	token := internal.TryToGetToken(slug, name)


	return 	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "",  "token",token)
}
	
func CNGuild(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj, err := StringGuild(ctx  ,realmSlug,nameSlug, )
if err != nil {
		return nil,err
	}
resp :=&GuildResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

func BNetGuild(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj ,err := CNGuild(ctx  ,realmSlug,nameSlug, )
if err != nil {
	return nil,err
}


return obj.(*GuildResponse).ToBNet(),nil
}

 
//GuildActivity Returns a single guild's activity by name and realm.
//@see: /data/wow/guild/{realmSlug}/{nameSlug}/activity

func StringGuildActivity(ctx context.Context,   ,
realmSlug string,nameSlug string,
)(string,error){
	client := utils.NewRequest()
	token := internal.TryToGetToken(slug, name)


	return 	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "",  "token",token)
}
	
func CNGuildActivity(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj, err := StringGuildActivity(ctx  ,realmSlug,nameSlug, )
if err != nil {
		return nil,err
	}
resp :=&GuildActivityResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

func BNetGuildActivity(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj ,err := CNGuildActivity(ctx  ,realmSlug,nameSlug, )
if err != nil {
	return nil,err
}


return obj.(*GuildActivityResponse).ToBNet(),nil
}

 
//GuildAchievements Returns a single guild's achievements by name and realm.
//@see: /data/wow/guild/{realmSlug}/{nameSlug}/achievements

func StringGuildAchievements(ctx context.Context,   ,
realmSlug string,nameSlug string,
)(string,error){
	client := utils.NewRequest()
	token := internal.TryToGetToken(slug, name)


	return 	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "",  "token",token)
}
	
func CNGuildAchievements(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj, err := StringGuildAchievements(ctx  ,realmSlug,nameSlug, )
if err != nil {
		return nil,err
	}
resp :=&GuildAchievementsResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

func BNetGuildAchievements(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj ,err := CNGuildAchievements(ctx  ,realmSlug,nameSlug, )
if err != nil {
	return nil,err
}


return obj.(*GuildAchievementsResponse).ToBNet(),nil
}

 
//GuildRoster Returns a single guild's roster by its name and realm.
//@see: /data/wow/guild/{realmSlug}/{nameSlug}/roster

func StringGuildRoster(ctx context.Context,   ,
realmSlug string,nameSlug string,
)(string,error){
	client := utils.NewRequest()
	token := internal.TryToGetToken(slug, name)


	return 	client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "",  "token",token)
}
	
func CNGuildRoster(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj, err := StringGuildRoster(ctx  ,realmSlug,nameSlug, )
if err != nil {
		return nil,err
	}
resp :=&GuildRosterResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

func BNetGuildRoster(ctx context.Context   ,
realmSlug string,nameSlug string,
)(any,error){

obj ,err := CNGuildRoster(ctx  ,realmSlug,nameSlug, )
if err != nil {
	return nil,err
}


return obj.(*GuildRosterResponse).ToBNet(),nil
}


