package SC_Profile
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetLadderResponse is the unified BNet representation for Ladder.
type BNetLadderResponse struct{}

// LadderResponse represents the raw CN API response for Ladder.
type LadderResponse BNetLadderResponse

// ToBNet converts the CN response to the unified BNetLadderResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *LadderResponse) ToBNet() any {
	return r 
}

