package wow_WoWToken

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


)


// ==============================================================================================
// API: WoWTokenIndex
// ==============================================================================================

type WoWTokenIndexFields struct {
	Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookWoWTokenIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookWoWTokenIndex func(context.Context, *WoWTokenIndexFields) (any, error)

// StringWoWTokenIndex executes the request and returns the raw response body string.
func StringWoWTokenIndex(ctx context.Context, fields *WoWTokenIndexFields) (string, error) {
	if fields == nil {
		fields = &WoWTokenIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("WoWTokenIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/token/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeWoWTokenIndex routes the request to either CN or Global logic based on input.
func bridgeWoWTokenIndex(ctx context.Context, fields *WoWTokenIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookWoWTokenIndex != nil {
			return CNHookWoWTokenIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringWoWTokenIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &WoWTokenIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// WoWTokenIndex
/* WoWTokenIndex Returns the WoW Token index. */
// Path: /data/wow/token/index
var WoWTokenIndex = bridgeWoWTokenIndex


// ==============================================================================================
// API: WoWTokenIndexCN
// ==============================================================================================

type WoWTokenIndexCNFields struct {
	Namespace string `form:"namespace,default=dynamic-cn"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=zh_CN"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookWoWTokenIndexCN allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookWoWTokenIndexCN func(context.Context, *WoWTokenIndexCNFields) (any, error)

// StringWoWTokenIndexCN executes the request and returns the raw response body string.
func StringWoWTokenIndexCN(ctx context.Context, fields *WoWTokenIndexCNFields) (string, error) {
	if fields == nil {
		fields = &WoWTokenIndexCNFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("WoWTokenIndexCN")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/token/index",
			CnRegion: true,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-cn"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "zh_CN"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-cn")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "zh_CN")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeWoWTokenIndexCN routes the request to either CN or Global logic based on input.
func bridgeWoWTokenIndexCN(ctx context.Context, fields *WoWTokenIndexCNFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookWoWTokenIndexCN != nil {
			return CNHookWoWTokenIndexCN(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringWoWTokenIndexCN(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &WoWTokenIndexCNModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// WoWTokenIndexCN
/* WoWTokenIndexCN Returns the WoW Token index. */
// Path: /data/wow/token/index
var WoWTokenIndexCN = bridgeWoWTokenIndexCN

