package wow_MythicRaidLeaderboard

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: MythicRaidLeaderboard
// ==============================================================================================

type MythicRaidLeaderboardFields struct {
	Raid string `uri:"raid" binding:"required"` // The raid for a leaderboard.
		Faction string `uri:"faction" binding:"required"` // Player faction (`alliance` or `horde`).
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookMythicRaidLeaderboard allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookMythicRaidLeaderboard func(context.Context, *MythicRaidLeaderboardFields) (any, error)

// StringMythicRaidLeaderboard executes the request and returns the raw response body string.
func StringMythicRaidLeaderboard(ctx context.Context, fields *MythicRaidLeaderboardFields) (string, error) {
	if fields == nil {
		fields = &MythicRaidLeaderboardFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("MythicRaidLeaderboard")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/leaderboard/hall-of-fame/{raid}/{faction}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Raid == "" {
		fields.Raid = "uldir"
	}
	
	
	if fields.Faction == "" {
		fields.Faction = "alliance"
	}
	
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"raid": fields.Raid,
    		"faction": fields.Faction,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeMythicRaidLeaderboard routes the request to either CN or Global logic based on input.
func bridgeMythicRaidLeaderboard(ctx context.Context, fields *MythicRaidLeaderboardFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookMythicRaidLeaderboard != nil {
			return CNHookMythicRaidLeaderboard(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringMythicRaidLeaderboard(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &MythicRaidLeaderboardModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// MythicRaidLeaderboard
/* MythicRaidLeaderboard Returns the leaderboard for a given raid and faction. */
// Path: /data/wow/leaderboard/hall-of-fame/{raid}/{faction}
var MythicRaidLeaderboard = bridgeMythicRaidLeaderboard

