package wowRetail_Heirloom
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type HeirloomIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func HeirloomIndexField(input *HeirloomIndexFields) *HeirloomIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/heirloom/index",
//			CnRegion:false ,
//}
//return input
//}


//HeirloomIndex Returns an index of heirlooms.
//
//@see: /data/wow/heirloom/index
func StringHeirloomIndex(ctx context.Context, fields *HeirloomIndexFields)(string,error){
	if fields == nil {
		fields = &HeirloomIndexFields{}
	}

	func(input *HeirloomIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/heirloom/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNHeirloomIndex(ctx context.Context, fields *HeirloomIndexFields)(any,error){

obj, err := StringHeirloomIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&HeirloomIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var HeirloomIndex = CNHeirloomIndex
/*func BNetHeirloomIndex(ctx context.Context, fields *HeirloomIndexFields)(any,error){

obj ,err := CNHeirloomIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*HeirloomIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type HeirloomFields struct{
	HeirloomId int//The ID of the heirloom.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func HeirloomField(input *HeirloomFields) *HeirloomFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/heirloom/{heirloomId}",
//			CnRegion:false ,
//}
//return input
//}


//Heirloom Returns an heirloom by id.
//
//@see: /data/wow/heirloom/{heirloomId}
func StringHeirloom(ctx context.Context, fields *HeirloomFields)(string,error){
	if fields == nil {
		fields = &HeirloomFields{}
	}

	func(input *HeirloomFields) {
	
if input.HeirloomId==0{
input.HeirloomId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/heirloom/{heirloomId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("heirloomId", strconv.Itoa(fields.HeirloomId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNHeirloom(ctx context.Context, fields *HeirloomFields)(any,error){

obj, err := StringHeirloom(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&HeirloomResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Heirloom = CNHeirloom
/*func BNetHeirloom(ctx context.Context, fields *HeirloomFields)(any,error){

obj ,err := CNHeirloom(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*HeirloomResponse).ToBNet(),nil
}*/


