package wow_Spell

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	
	    "strconv"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: Spell
// ==============================================================================================

type SpellFields struct {
	SpellId int `uri:"spellId" binding:"required"` // The ID of the spell.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookSpell allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookSpell func(context.Context, *SpellFields) (any, error)

// StringSpell executes the request and returns the raw response body string.
func StringSpell(ctx context.Context, fields *SpellFields) (string, error) {
	if fields == nil {
		fields = &SpellFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("Spell")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/spell/{spellId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.SpellId == 0 {
		fields.SpellId = 196607
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"spellId": fields.SpellId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeSpell routes the request to either CN or Global logic based on input.
func bridgeSpell(ctx context.Context, fields *SpellFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookSpell != nil {
			return CNHookSpell(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringSpell(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &SpellModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// Spell
/* Spell Returns a spell by ID. */
// Path: /data/wow/spell/{spellId}
var Spell = bridgeSpell


// ==============================================================================================
// API: SpellMedia
// ==============================================================================================

type SpellMediaFields struct {
	SpellId int `uri:"spellId" binding:"required"` // The ID of the spell.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookSpellMedia allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookSpellMedia func(context.Context, *SpellMediaFields) (any, error)

// StringSpellMedia executes the request and returns the raw response body string.
func StringSpellMedia(ctx context.Context, fields *SpellMediaFields) (string, error) {
	if fields == nil {
		fields = &SpellMediaFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("SpellMedia")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/media/spell/{spellId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.SpellId == 0 {
		fields.SpellId = 196607
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"spellId": fields.SpellId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeSpellMedia routes the request to either CN or Global logic based on input.
func bridgeSpellMedia(ctx context.Context, fields *SpellMediaFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookSpellMedia != nil {
			return CNHookSpellMedia(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringSpellMedia(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &SpellMediaModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SpellMedia
/* SpellMedia Returns media for a spell by ID. */
// Path: /data/wow/media/spell/{spellId}
var SpellMedia = bridgeSpellMedia


// ==============================================================================================
// API: SpellSearch
// ==============================================================================================

type SpellSearchFields struct {
	Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Nameen_US string `form:"nameen_US,default=Holy Shield"` // The name of the spell. (example search field)
	Orderby string `form:"orderby,default=id"` // The field to sort the result set by.
	_page int `form:"_page,default=1"` // The result page number.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookSpellSearch allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookSpellSearch func(context.Context, *SpellSearchFields) (any, error)

// StringSpellSearch executes the request and returns the raw response body string.
func StringSpellSearch(ctx context.Context, fields *SpellSearchFields) (string, error) {
	if fields == nil {
		fields = &SpellSearchFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("SpellSearch")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/search/spell",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Nameen_US == "" {
		fields.Nameen_US = "Holy Shield"
	}
	
	
	if fields.Orderby == "" {
		fields.Orderby = "id"
	}
	
	
	if fields._page == 0 {
		fields._page = 1
	}
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("nameen_US") {
		q.Add("nameen_US", "Holy Shield")
	}
    
    
	if !q.Has("orderby") {
		q.Add("orderby", "id")
	}
    
    
    	if !q.Has("_page") {
    		q.Add("_page", strconv.Itoa(fields._page))
    	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeSpellSearch routes the request to either CN or Global logic based on input.
func bridgeSpellSearch(ctx context.Context, fields *SpellSearchFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookSpellSearch != nil {
			return CNHookSpellSearch(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringSpellSearch(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &SpellSearchModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// SpellSearch
/* SpellSearch Performs a search of spells. The fields below are provided for example. For more detail see the <a href="/documentation/world-of-warcraft/guides/search">Search Guide</a>. */
// Path: /data/wow/search/spell
var SpellSearch = bridgeSpellSearch

