package wowRetail_Spell
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type SpellFields struct{
	SpellId int//The ID of the spell.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SpellField(input *SpellFields) *SpellFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/spell/{spellId}",
//			CnRegion:false ,
//}
//return input
//}


//Spell Returns a spell by ID.
//
//@see: /data/wow/spell/{spellId}
func StringSpell(ctx context.Context, fields *SpellFields)(string,error){
	if fields == nil {
		fields = &SpellFields{}
	}

	func(input *SpellFields) {
	
if input.SpellId==0{
input.SpellId = 196607
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/spell/{spellId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("spellId", strconv.Itoa(fields.SpellId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSpell(ctx context.Context, fields *SpellFields)(any,error){

obj, err := StringSpell(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SpellResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Spell = CNSpell
/*func BNetSpell(ctx context.Context, fields *SpellFields)(any,error){

obj ,err := CNSpell(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SpellResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type SpellMediaFields struct{
	SpellId int//The ID of the spell.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SpellMediaField(input *SpellMediaFields) *SpellMediaFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/media/spell/{spellId}",
//			CnRegion:false ,
//}
//return input
//}


//SpellMedia Returns media for a spell by ID.
//
//@see: /data/wow/media/spell/{spellId}
func StringSpellMedia(ctx context.Context, fields *SpellMediaFields)(string,error){
	if fields == nil {
		fields = &SpellMediaFields{}
	}

	func(input *SpellMediaFields) {
	
if input.SpellId==0{
input.SpellId = 196607
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/media/spell/{spellId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("spellId", strconv.Itoa(fields.SpellId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSpellMedia(ctx context.Context, fields *SpellMediaFields)(any,error){

obj, err := StringSpellMedia(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SpellMediaResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var SpellMedia = CNSpellMedia
/*func BNetSpellMedia(ctx context.Context, fields *SpellMediaFields)(any,error){

obj ,err := CNSpellMedia(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SpellMediaResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type SpellSearchFields struct{
	Namespace string//The namespace to use to locate this document.
	NameDoten_US string//The name of the spell. (example search field)
	Orderby string//The field to sort the result set by.
	_page int//The result page number.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SpellSearchField(input *SpellSearchFields) *SpellSearchFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/search/spell",
//			CnRegion:false ,
//}
//return input
//}


//SpellSearch Performs a search of spells. The fields below are provided for example. For more detail see the <a href="/documentation/world-of-warcraft/guides/search">Search Guide</a>.
//
//@see: /data/wow/search/spell
func StringSpellSearch(ctx context.Context, fields *SpellSearchFields)(string,error){
	if fields == nil {
		fields = &SpellSearchFields{}
	}

	func(input *SpellSearchFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.NameDoten_US==""{
input.NameDoten_US = "Holy Shield"
}

	
if input.Orderby==""{
input.Orderby = "id"
}

	
if input._page==0{
input._page = 1
}
	
	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/search/spell",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("nameDoten_US", fields.NameDoten_US)
	q.Add("orderby", fields.Orderby)
	q.Add("_page", strconv.Itoa(fields._page))
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSpellSearch(ctx context.Context, fields *SpellSearchFields)(any,error){

obj, err := StringSpellSearch(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SpellSearchResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var SpellSearch = CNSpellSearch
/*func BNetSpellSearch(ctx context.Context, fields *SpellSearchFields)(any,error){

obj ,err := CNSpellSearch(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SpellSearchResponse).ToBNet(),nil
}*/


