package wowRetail_Spell
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetSpellResponse is the unified BNet representation for Spell.
type BNetSpellResponse struct{}

// SpellResponse represents the raw CN API response for Spell.
type SpellResponse BNetSpellResponse

// ToBNet converts the CN response to the unified BNetSpellResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *SpellResponse) ToBNet() any {
	return r 
}

