package wow_CharacterMythicKeystoneProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

import "github.com/jinzhu/copier"

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterMythicKeystoneProfileIndexResponse is the unified BNet representation for CharacterMythicKeystoneProfileIndex.
type BNetCharacterMythicKeystoneProfileIndexResponse struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	CurrentPeriod struct {
		Period struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Id int `json:"id"`
		} `json:"period"`
		BestRuns []struct {
			CompletedTimestamp int64 `json:"completed_timestamp"`
			Duration           int   `json:"duration"`
			KeystoneLevel      int   `json:"keystone_level"`
			KeystoneAffixes    []struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"keystone_affixes"`
			Members []struct {
				Character struct {
					Name  string `json:"name"`
					Id    int    `json:"id"`
					Realm struct {
						Key struct {
							Href string `json:"href"`
						} `json:"key"`
						Id   int    `json:"id"`
						Slug string `json:"slug"`
					} `json:"realm"`
				} `json:"character"`
				Specialization struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Name string `json:"name"`
					Id   int    `json:"id"`
				} `json:"specialization"`
				Race struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Name string `json:"name"`
					Id   int    `json:"id"`
				} `json:"race"`
				EquippedItemLevel int `json:"equipped_item_level"`
			} `json:"members"`
			Dungeon struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"dungeon"`
			IsCompletedWithinTime bool `json:"is_completed_within_time"`
			MythicRating          struct {
				Color struct {
					R int `json:"r"`
					G int `json:"g"`
					B int `json:"b"`
					A int `json:"a"`
				} `json:"color"`
				Rating float64 `json:"rating"`
			} `json:"mythic_rating"`
			MapRating struct {
				Color struct {
					R int `json:"r"`
					G int `json:"g"`
					B int `json:"b"`
					A int `json:"a"`
				} `json:"color"`
				Rating float64 `json:"rating"`
			} `json:"map_rating"`
		} `json:"best_runs"`
	} `json:"current_period"`
	Seasons []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Id int `json:"id"`
	} `json:"seasons"`
	Character struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	CurrentMythicRating struct {
		Color  Color   `json:"color"`
		Rating float64 `json:"rating"`
	} `json:"current_mythic_rating"`
}

type Color struct {
	R int `json:"r"`
	G int `json:"g"`
	B int `json:"b"`
	A int `json:"a"`
}

// CharacterMythicKeystoneProfileIndexResponse represents the raw CN API response for CharacterMythicKeystoneProfileIndex.
type CharacterMythicKeystoneProfileIndexResponse struct {
	BestRuns []struct {
		CompletedTimestamp int64 `json:"completed_timestamp"`
		Dungeon            struct {
			Icon string `json:"icon"`
			Id   int    `json:"id"`
			Key  struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
		} `json:"dungeon"`
		Duration              int  `json:"duration"`
		IsCompletedWithinTime bool `json:"is_completed_within_time"`
		KeystoneAffixes       []struct {
			Description string `json:"description"`
			Icon        string `json:"icon"`
			Id          int    `json:"id"`
			Name        string `json:"name"`
		} `json:"keystone_affixes"`
		KeystoneLevel int `json:"keystone_level"`
		MapRating     struct {
			Color struct {
				A int `json:"a"`
				B int `json:"b"`
				G int `json:"g"`
				R int `json:"r"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"map_rating"`
		Members []struct {
			Character struct {
				CharacterId string `json:"character_id"`
				ClassId     int    `json:"class_id"`
				Id          int    `json:"id"`
				Name        string `json:"name"`
				Realm       struct {
					Id   int    `json:"id"`
					Slug string `json:"slug"`
				} `json:"realm"`
			} `json:"character"`
			EquippedItemLevel int `json:"equipped_item_level"`
			Race              struct {
				Id   int    `json:"id"`
				Name string `json:"name"`
			} `json:"race"`
			Specialization struct {
				Id   int    `json:"id"`
				Name string `json:"name"`
			} `json:"specialization"`
		} `json:"members"`
		MythicRating struct {
			Color struct {
				A int `json:"a"`
				B int `json:"b"`
				G int `json:"g"`
				R int `json:"r"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"mythic_rating"`
	} `json:"best_runs"`
	Character struct {
		Id  int `json:"id"`
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Realm struct {
			Id  int `json:"id"`
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	MythicRating struct {
		Color struct {
			A int `json:"a"`
			B int `json:"b"`
			G int `json:"g"`
			R int `json:"r"`
		} `json:"color"`
		Rating float64 `json:"rating"`
	} `json:"mythic_rating"`
	Season struct {
		Key struct {
			Href string `json:"href"`
		} `json:"Key"`
		Id        int    `json:"id"`
		SeasonStr string `json:"season_str"`
	} `json:"season"`
}

// ToBNet converts the CN response to the unified BNetCharacterMythicKeystoneProfileIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterMythicKeystoneProfileIndexResponse) ToBNet() any {
	b := &BNetCharacterMythicKeystoneProfileIndexResponse{}
	copier.Copy(b, r)
	return b
}
