package wow_CharacterMythicKeystoneProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterMythicKeystoneSeasonDetailsResponse is the unified BNet representation for CharacterMythicKeystoneSeasonDetails.
type BNetCharacterMythicKeystoneSeasonDetailsResponse struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Season struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Id int `json:"id"`
	} `json:"season"`
	BestRuns []struct {
		CompletedTimestamp int64 `json:"completed_timestamp"`
		Duration           int   `json:"duration"`
		KeystoneLevel      int   `json:"keystone_level"`
		KeystoneAffixes    []struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"keystone_affixes"`
		Members []struct {
			Character struct {
				Name  string `json:"name"`
				Id    int    `json:"id"`
				Realm struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Id   int    `json:"id"`
					Slug string `json:"slug"`
				} `json:"realm"`
			} `json:"character"`
			Specialization struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"specialization"`
			Race struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"race"`
			EquippedItemLevel int `json:"equipped_item_level"`
		} `json:"members"`
		Dungeon struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"dungeon"`
		IsCompletedWithinTime bool `json:"is_completed_within_time"`
		MythicRating          struct {
			Color struct {
				R int `json:"r"`
				G int `json:"g"`
				B int `json:"b"`
				A int `json:"a"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"mythic_rating"`
		MapRating struct {
			Color struct {
				R int `json:"r"`
				G int `json:"g"`
				B int `json:"b"`
				A int `json:"a"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"map_rating"`
	} `json:"best_runs"`
	Character struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	MythicRating struct {
		Color struct {
			R int `json:"r"`
			G int `json:"g"`
			B int `json:"b"`
			A int `json:"a"`
		} `json:"color"`
		Rating float64 `json:"rating"`
	} `json:"mythic_rating"`
}

// CharacterMythicKeystoneSeasonDetailsResponse represents the raw CN API response for CharacterMythicKeystoneSeasonDetails.
type CharacterMythicKeystoneSeasonDetailsResponse struct {
	Season struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Id int `json:"id"`
	} `json:"season"`
	BestRuns []struct {
		CompletedTimestamp int64 `json:"completed_timestamp"`
		Duration           int   `json:"duration"`
		KeystoneLevel      int   `json:"keystone_level"`
		KeystoneAffixes    []struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"keystone_affixes"`
		Members []struct {
			Character struct {
				Name  string `json:"name"`
				Id    int    `json:"id"`
				Realm struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Id   int    `json:"id"`
					Slug string `json:"slug"`
				} `json:"realm"`
			} `json:"character"`
			Specialization struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"specialization"`
			Race struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				Name string `json:"name"`
				Id   int    `json:"id"`
			} `json:"race"`
			EquippedItemLevel int `json:"equipped_item_level"`
		} `json:"members"`
		Dungeon struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"dungeon"`
		IsCompletedWithinTime bool `json:"is_completed_within_time"`
		MythicRating          struct {
			Color struct {
				R int `json:"r"`
				G int `json:"g"`
				B int `json:"b"`
				A int `json:"a"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"mythic_rating"`
		MapRating struct {
			Color struct {
				R int `json:"r"`
				G int `json:"g"`
				B int `json:"b"`
				A int `json:"a"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"map_rating"`
	} `json:"best_runs"`
	Character struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	MythicRating struct {
		Color struct {
			R int `json:"r"`
			G int `json:"g"`
			B int `json:"b"`
			A int `json:"a"`
		} `json:"color"`
		Rating float64 `json:"rating"`
	} `json:"mythic_rating"`
}

// ToBNet converts the CN response to the unified BNetCharacterMythicKeystoneSeasonDetailsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterMythicKeystoneSeasonDetailsResponse) ToBNet() any {
	return r
}
