package wowRetail_Pet
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPetAbilityResponse is the unified BNet representation for PetAbility.
type BNetPetAbilityResponse struct{}

// PetAbilityResponse represents the raw CN API response for PetAbility.
type PetAbilityResponse BNetPetAbilityResponse

// ToBNet converts the CN response to the unified BNetPetAbilityResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PetAbilityResponse) ToBNet() any {
	return r 
}

