package wowRetail_Pet
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPetsIndexResponse is the unified BNet representation for PetsIndex.
type BNetPetsIndexResponse struct{}

// PetsIndexResponse represents the raw CN API response for PetsIndex.
type PetsIndexResponse BNetPetsIndexResponse

// ToBNet converts the CN response to the unified BNetPetsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PetsIndexResponse) ToBNet() any {
	return r 
}

