package wowRetail_Talent
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPvPTalentsIndexResponse is the unified BNet representation for PvPTalentsIndex.
type BNetPvPTalentsIndexResponse struct{}

// PvPTalentsIndexResponse represents the raw CN API response for PvPTalentsIndex.
type PvPTalentsIndexResponse BNetPvPTalentsIndexResponse

// ToBNet converts the CN response to the unified BNetPvPTalentsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PvPTalentsIndexResponse) ToBNet() any {
	return r 
}

