package wowRetail_Talent
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetTalentTreeNodesResponse is the unified BNet representation for TalentTreeNodes.
type BNetTalentTreeNodesResponse struct{}

// TalentTreeNodesResponse represents the raw CN API response for TalentTreeNodes.
type TalentTreeNodesResponse BNetTalentTreeNodesResponse

// ToBNet converts the CN response to the unified BNetTalentTreeNodesResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *TalentTreeNodesResponse) ToBNet() any {
	return r 
}

