package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/jtacoma/uritemplates"
)

//==============================================================================================

type CharacterCollectionsIndexFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterCollectionsIndexField(input *CharacterCollectionsIndexFields) *CharacterCollectionsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterCollectionsIndex(ctx context.Context, fields *CharacterCollectionsIndexFields) (string, error) {
	if fields == nil {
		fields = &CharacterCollectionsIndexFields{}
	}

	func(input *CharacterCollectionsIndexFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterCollectionsIndex(ctx context.Context, fields *CharacterCollectionsIndexFields) (any, error) {

	obj, err := cnStringCharacterCollectionsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                `json:"code"`
		Message string                             `json:"message"`
		Data    *CharacterCollectionsIndexResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterCollectionsIndex(ctx context.Context, fields *CharacterCollectionsIndexFields) (string, error) {
	return "", ApiError.ErrorNotSupported
}

func bridgeCharacterCollectionsIndex(ctx context.Context, fields *CharacterCollectionsIndexFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterCollectionsIndex(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterCollectionsIndexResponse).ToBNet(), nil
	}
	obj, err := StringCharacterCollectionsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterCollectionsIndexResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterCollectionsIndex Returns an index of collection types for a character.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections
var CharacterCollectionsIndex = bridgeCharacterCollectionsIndex

//==============================================================================================

type CharacterDecorCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterDecorCollectionSummaryField(input *CharacterDecorCollectionSummaryFields) *CharacterDecorCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/decor",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterDecorCollectionSummary(ctx context.Context, fields *CharacterDecorCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterDecorCollectionSummaryFields{}
	}

	func(input *CharacterDecorCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/decor",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterDecorCollectionSummary(ctx context.Context, fields *CharacterDecorCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterDecorCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                      `json:"code"`
		Message string                                   `json:"message"`
		Data    *CharacterDecorCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterDecorCollectionSummary(ctx context.Context, fields *CharacterDecorCollectionSummaryFields) (string, error) {
	return "", ApiError.ErrorNotSupported
}

func bridgeCharacterDecorCollectionSummary(ctx context.Context, fields *CharacterDecorCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterDecorCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterDecorCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterDecorCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterDecorCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterDecorCollectionSummary Returns a summary of the housing decor collection a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/decor
var CharacterDecorCollectionSummary = bridgeCharacterDecorCollectionSummary

//==============================================================================================

type CharacterHeirloomsCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterHeirloomsCollectionSummaryField(input *CharacterHeirloomsCollectionSummaryFields) *CharacterHeirloomsCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/heirlooms",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterHeirloomsCollectionSummary(ctx context.Context, fields *CharacterHeirloomsCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterHeirloomsCollectionSummaryFields{}
	}

	func(input *CharacterHeirloomsCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/heirlooms",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterHeirloomsCollectionSummary(ctx context.Context, fields *CharacterHeirloomsCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterHeirloomsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                          `json:"code"`
		Message string                                       `json:"message"`
		Data    *CharacterHeirloomsCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterHeirloomsCollectionSummary(ctx context.Context, fields *CharacterHeirloomsCollectionSummaryFields) (string, error) {
	return "", ApiError.ErrorNotSupported
}

func bridgeCharacterHeirloomsCollectionSummary(ctx context.Context, fields *CharacterHeirloomsCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterHeirloomsCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterHeirloomsCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterHeirloomsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterHeirloomsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterHeirloomsCollectionSummary Returns a summary of the heirlooms a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/heirlooms
var CharacterHeirloomsCollectionSummary = bridgeCharacterHeirloomsCollectionSummary

//==============================================================================================

type CharacterMountsCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterMountsCollectionSummaryField(input *CharacterMountsCollectionSummaryFields) *CharacterMountsCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/mounts",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterMountsCollectionSummary(ctx context.Context, fields *CharacterMountsCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterMountsCollectionSummaryFields{}
	}

	func(input *CharacterMountsCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/mounts",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterMountsCollectionSummary(ctx context.Context, fields *CharacterMountsCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterMountsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                       `json:"code"`
		Message string                                    `json:"message"`
		Data    *CharacterMountsCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterMountsCollectionSummary(ctx context.Context, fields *CharacterMountsCollectionSummaryFields) (string, error) {

	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "mounts", "token", token)
}

func bridgeCharacterMountsCollectionSummary(ctx context.Context, fields *CharacterMountsCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterMountsCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterMountsCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterMountsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterMountsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterMountsCollectionSummary Returns a summary of the mounts a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/mounts
var CharacterMountsCollectionSummary = bridgeCharacterMountsCollectionSummary

//==============================================================================================

type CharacterPetsCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterPetsCollectionSummaryField(input *CharacterPetsCollectionSummaryFields) *CharacterPetsCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/pets",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterPetsCollectionSummary(ctx context.Context, fields *CharacterPetsCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterPetsCollectionSummaryFields{}
	}

	func(input *CharacterPetsCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/pets",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterPetsCollectionSummary(ctx context.Context, fields *CharacterPetsCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterPetsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                     `json:"code"`
		Message string                                  `json:"message"`
		Data    *CharacterPetsCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterPetsCollectionSummary(ctx context.Context, fields *CharacterPetsCollectionSummaryFields) (string, error) {

	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "pets", "token", token)
}

func bridgeCharacterPetsCollectionSummary(ctx context.Context, fields *CharacterPetsCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterPetsCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterPetsCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterPetsCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterPetsCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterPetsCollectionSummary Returns a summary of the battle pets a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/pets
var CharacterPetsCollectionSummary = bridgeCharacterPetsCollectionSummary

//==============================================================================================

type CharacterToysCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterToysCollectionSummaryField(input *CharacterToysCollectionSummaryFields) *CharacterToysCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/toys",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterToysCollectionSummary(ctx context.Context, fields *CharacterToysCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterToysCollectionSummaryFields{}
	}

	func(input *CharacterToysCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/toys",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterToysCollectionSummary(ctx context.Context, fields *CharacterToysCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterToysCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                     `json:"code"`
		Message string                                  `json:"message"`
		Data    *CharacterToysCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterToysCollectionSummary(ctx context.Context, fields *CharacterToysCollectionSummaryFields) (string, error) {
	return "", ApiError.ErrorNotSupported
}

func bridgeCharacterToysCollectionSummary(ctx context.Context, fields *CharacterToysCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterToysCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterToysCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterToysCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterToysCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterToysCollectionSummary Returns a summary of the toys a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/toys
var CharacterToysCollectionSummary = bridgeCharacterToysCollectionSummary

//==============================================================================================

type CharacterTransmogCollectionSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterTransmogCollectionSummaryField(input *CharacterTransmogCollectionSummaryFields) *CharacterTransmogCollectionSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/collections/transmogs",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterTransmogCollectionSummary(ctx context.Context, fields *CharacterTransmogCollectionSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterTransmogCollectionSummaryFields{}
	}

	func(input *CharacterTransmogCollectionSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/collections/transmogs",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterTransmogCollectionSummary(ctx context.Context, fields *CharacterTransmogCollectionSummaryFields) (any, error) {

	obj, err := cnStringCharacterTransmogCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                         `json:"code"`
		Message string                                      `json:"message"`
		Data    *CharacterTransmogCollectionSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterTransmogCollectionSummary(ctx context.Context, fields *CharacterTransmogCollectionSummaryFields) (string, error) {
	return "", ApiError.ErrorNotSupported
}

func bridgeCharacterTransmogCollectionSummary(ctx context.Context, fields *CharacterTransmogCollectionSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterTransmogCollectionSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterTransmogCollectionSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterTransmogCollectionSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterTransmogCollectionSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterTransmogCollectionSummary Returns a summary of the transmog unlocks a character has obtained.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/collections/transmogs
var CharacterTransmogCollectionSummary = bridgeCharacterTransmogCollectionSummary
