package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterTransmogCollectionSummaryResponse is the unified BNet representation for CharacterTransmogCollectionSummary.
type BNetCharacterTransmogCollectionSummaryResponse struct{}

// CharacterTransmogCollectionSummaryResponse represents the raw CN API response for CharacterTransmogCollectionSummary.
type CharacterTransmogCollectionSummaryResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterTransmogCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterTransmogCollectionSummaryResponse) ToBNet() any {
	return nil
}
