package wowRetail_PlayableSpecialization
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type PlayableSpecializationsIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PlayableSpecializationsIndexField(input *PlayableSpecializationsIndexFields) *PlayableSpecializationsIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/playable-specialization/index",
//			CnRegion:false ,
//}
//return input
//}


//PlayableSpecializationsIndex Returns an index of playable specializations.
//
//@see: /data/wow/playable-specialization/index
func StringPlayableSpecializationsIndex(ctx context.Context, fields *PlayableSpecializationsIndexFields)(string,error){
	if fields == nil {
		fields = &PlayableSpecializationsIndexFields{}
	}

	func(input *PlayableSpecializationsIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/playable-specialization/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPlayableSpecializationsIndex(ctx context.Context, fields *PlayableSpecializationsIndexFields)(any,error){

obj, err := StringPlayableSpecializationsIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PlayableSpecializationsIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PlayableSpecializationsIndex = CNPlayableSpecializationsIndex
/*func BNetPlayableSpecializationsIndex(ctx context.Context, fields *PlayableSpecializationsIndexFields)(any,error){

obj ,err := CNPlayableSpecializationsIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PlayableSpecializationsIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PlayableSpecializationFields struct{
	SpecId int//The ID of the playable specialization.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PlayableSpecializationField(input *PlayableSpecializationFields) *PlayableSpecializationFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/playable-specialization/{specId}",
//			CnRegion:false ,
//}
//return input
//}


//PlayableSpecialization Returns a playable specialization by ID.
//
//@see: /data/wow/playable-specialization/{specId}
func StringPlayableSpecialization(ctx context.Context, fields *PlayableSpecializationFields)(string,error){
	if fields == nil {
		fields = &PlayableSpecializationFields{}
	}

	func(input *PlayableSpecializationFields) {
	
if input.SpecId==0{
input.SpecId = 262
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/playable-specialization/{specId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("specId", strconv.Itoa(fields.SpecId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPlayableSpecialization(ctx context.Context, fields *PlayableSpecializationFields)(any,error){

obj, err := StringPlayableSpecialization(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PlayableSpecializationResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PlayableSpecialization = CNPlayableSpecialization
/*func BNetPlayableSpecialization(ctx context.Context, fields *PlayableSpecializationFields)(any,error){

obj ,err := CNPlayableSpecialization(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PlayableSpecializationResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type PlayableSpecializationMediaFields struct{
	SpecId int//The ID of the playable specialization.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func PlayableSpecializationMediaField(input *PlayableSpecializationMediaFields) *PlayableSpecializationMediaFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/media/playable-specialization/{specId}",
//			CnRegion:false ,
//}
//return input
//}


//PlayableSpecializationMedia Returns media for a playable specialization by ID.
//
//@see: /data/wow/media/playable-specialization/{specId}
func StringPlayableSpecializationMedia(ctx context.Context, fields *PlayableSpecializationMediaFields)(string,error){
	if fields == nil {
		fields = &PlayableSpecializationMediaFields{}
	}

	func(input *PlayableSpecializationMediaFields) {
	
if input.SpecId==0{
input.SpecId = 262
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/media/playable-specialization/{specId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("specId", strconv.Itoa(fields.SpecId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNPlayableSpecializationMedia(ctx context.Context, fields *PlayableSpecializationMediaFields)(any,error){

obj, err := StringPlayableSpecializationMedia(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&PlayableSpecializationMediaResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var PlayableSpecializationMedia = CNPlayableSpecializationMedia
/*func BNetPlayableSpecializationMedia(ctx context.Context, fields *PlayableSpecializationMediaFields)(any,error){

obj ,err := CNPlayableSpecializationMedia(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*PlayableSpecializationMediaResponse).ToBNet(),nil
}*/


