package wowRetail_PlayableSpecialization
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPlayableSpecializationsIndexResponse is the unified BNet representation for PlayableSpecializationsIndex.
type BNetPlayableSpecializationsIndexResponse struct{}

// PlayableSpecializationsIndexResponse represents the raw CN API response for PlayableSpecializationsIndex.
type PlayableSpecializationsIndexResponse BNetPlayableSpecializationsIndexResponse

// ToBNet converts the CN response to the unified BNetPlayableSpecializationsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PlayableSpecializationsIndexResponse) ToBNet() any {
	return r 
}

