package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
)

//==============================================================================================

type getApiAccountFields struct {
	Account string //The BattleTag for the account to retrieve.
	Locale  string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func getApiAccountField(input *getApiAccountFields) *getApiAccountFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/d3/profile/{account}/",
//			CnRegion:false ,
//}
//return input
//}

// getApiAccount Returns the specified account profile.
//
// @see: /d3/profile/{account}/
func StringgetApiAccount(ctx context.Context, fields *getApiAccountFields) (string, error) {
	if fields == nil {
		fields = &getApiAccountFields{}
	}

	func(input *getApiAccountFields) {

		if input.Account == "" {
			input.Account = "<no value>"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/d3/profile/{account}/",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("account", fields.Account)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNgetApiAccount(ctx context.Context, fields *getApiAccountFields) (any, error) {

	obj, err := StringgetApiAccount(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &getApiAccountResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

var getApiAccount = CNgetApiAccount

/*func BNetgetApiAccount(ctx context.Context, fields *getApiAccountFields)(any,error){

obj ,err := CNgetApiAccount(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*getApiAccountResponse).ToBNet(),nil
}*/

//==============================================================================================

type getApiHeroFields struct {
	Account string //The BattleTag for the account to retrieve.
	HeroId  string //The ID of the hero to retrieve.
	Locale  string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func getApiHeroField(input *getApiHeroFields) *getApiHeroFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/d3/profile/{account}/hero/{heroId}",
//			CnRegion:false ,
//}
//return input
//}

// getApiHero Returns a single hero.
//
// @see: /d3/profile/{account}/hero/{heroId}
func StringgetApiHero(ctx context.Context, fields *getApiHeroFields) (string, error) {
	if fields == nil {
		fields = &getApiHeroFields{}
	}

	func(input *getApiHeroFields) {

		if input.Account == "" {
			input.Account = "<no value>"
		}

		if input.HeroId == "" {
			input.HeroId = "<no value>"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/d3/profile/{account}/hero/{heroId}",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("account", fields.Account)
	q.Add("heroId", fields.HeroId)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNgetApiHero(ctx context.Context, fields *getApiHeroFields) (any, error) {

	obj, err := StringgetApiHero(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &getApiHeroResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

var getApiHero = CNgetApiHero

/*func BNetgetApiHero(ctx context.Context, fields *getApiHeroFields)(any,error){

obj ,err := CNgetApiHero(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*getApiHeroResponse).ToBNet(),nil
}*/

//==============================================================================================

type getApiDetailedHeroItemsFields struct {
	Account string //The BattleTag for the account to retrieve.
	HeroId  string //The ID of the hero to retrieve.
	Locale  string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func getApiDetailedHeroItemsField(input *getApiDetailedHeroItemsFields) *getApiDetailedHeroItemsFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/d3/profile/{account}/hero/{heroId}/items",
//			CnRegion:false ,
//}
//return input
//}

// getApiDetailedHeroItems Returns a list of items for the specified hero.
//
// @see: /d3/profile/{account}/hero/{heroId}/items
func StringgetApiDetailedHeroItems(ctx context.Context, fields *getApiDetailedHeroItemsFields) (string, error) {
	if fields == nil {
		fields = &getApiDetailedHeroItemsFields{}
	}

	func(input *getApiDetailedHeroItemsFields) {

		if input.Account == "" {
			input.Account = "<no value>"
		}

		if input.HeroId == "" {
			input.HeroId = "<no value>"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/d3/profile/{account}/hero/{heroId}/items",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("account", fields.Account)
	q.Add("heroId", fields.HeroId)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNgetApiDetailedHeroItems(ctx context.Context, fields *getApiDetailedHeroItemsFields) (any, error) {

	obj, err := StringgetApiDetailedHeroItems(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &getApiDetailedHeroItemsResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

var getApiDetailedHeroItems = CNgetApiDetailedHeroItems

/*func BNetgetApiDetailedHeroItems(ctx context.Context, fields *getApiDetailedHeroItemsFields)(any,error){

obj ,err := CNgetApiDetailedHeroItems(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*getApiDetailedHeroItemsResponse).ToBNet(),nil
}*/

//==============================================================================================

type getApiDetailedFollowerItemsFields struct {
	Account string //The BattleTag for the account to retrieve.
	HeroId  string //The ID of the hero to retrieve.
	Locale  string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func getApiDetailedFollowerItemsField(input *getApiDetailedFollowerItemsFields) *getApiDetailedFollowerItemsFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/d3/profile/{account}/hero/{heroId}/follower-items",
//			CnRegion:false ,
//}
//return input
//}

// getApiDetailedFollowerItems Returns a list of items for the specified hero's followers.
//
// @see: /d3/profile/{account}/hero/{heroId}/follower-items
func StringgetApiDetailedFollowerItems(ctx context.Context, fields *getApiDetailedFollowerItemsFields) (string, error) {
	if fields == nil {
		fields = &getApiDetailedFollowerItemsFields{}
	}

	func(input *getApiDetailedFollowerItemsFields) {

		if input.Account == "" {
			input.Account = "<no value>"
		}

		if input.HeroId == "" {
			input.HeroId = "<no value>"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/d3/profile/{account}/hero/{heroId}/follower-items",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("account", fields.Account)
	q.Add("heroId", fields.HeroId)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNgetApiDetailedFollowerItems(ctx context.Context, fields *getApiDetailedFollowerItemsFields) (any, error) {

	obj, err := StringgetApiDetailedFollowerItems(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &getApiDetailedFollowerItemsResponse{}
	err = json.Unmarshal([]byte(obj), resp)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

var getApiDetailedFollowerItems = CNgetApiDetailedFollowerItems

/*func BNetgetApiDetailedFollowerItems(ctx context.Context, fields *getApiDetailedFollowerItemsFields)(any,error){

obj ,err := CNgetApiDetailedFollowerItems(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*getApiDetailedFollowerItemsResponse).ToBNet(),nil
}*/
