package D3_D3Profile
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetgetApiAccountResponse is the unified BNet representation for getApiAccount.
type BNetgetApiAccountResponse struct{}

// getApiAccountResponse represents the raw CN API response for getApiAccount.
type getApiAccountResponse BNetgetApiAccountResponse

// ToBNet converts the CN response to the unified BNetgetApiAccountResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *getApiAccountResponse) ToBNet() any {
	return r 
}

