package D3_D3Profile
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetgetApiHeroResponse is the unified BNet representation for getApiHero.
type BNetgetApiHeroResponse struct{}

// getApiHeroResponse represents the raw CN API response for getApiHero.
type getApiHeroResponse BNetgetApiHeroResponse

// ToBNet converts the CN response to the unified BNetgetApiHeroResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *getApiHeroResponse) ToBNet() any {
	return r 
}

