package wowRetail_Quest
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetQuestCategoriesIndexResponse is the unified BNet representation for QuestCategoriesIndex.
type BNetQuestCategoriesIndexResponse struct{}

// QuestCategoriesIndexResponse represents the raw CN API response for QuestCategoriesIndex.
type QuestCategoriesIndexResponse BNetQuestCategoriesIndexResponse

// ToBNet converts the CN response to the unified BNetQuestCategoriesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *QuestCategoriesIndexResponse) ToBNet() any {
	return r 
}

