package wowRetail_Quest
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetQuestTypesIndexResponse is the unified BNet representation for QuestTypesIndex.
type BNetQuestTypesIndexResponse struct{}

// QuestTypesIndexResponse represents the raw CN API response for QuestTypesIndex.
type QuestTypesIndexResponse BNetQuestTypesIndexResponse

// ToBNet converts the CN response to the unified BNetQuestTypesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *QuestTypesIndexResponse) ToBNet() any {
	return r 
}

