package wowClassic
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance


// BNetCharacterProfileSummaryResponse is the unified BNet representation for CharacterProfileSummary.
type BNetCharacterProfileSummaryResponse struct{}

// CharacterProfileSummaryResponse represents the raw CN API response for CharacterProfileSummary.
type CharacterProfileSummaryResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterProfileSummaryResponse) ToBNet() any {
	return nil
}

