package wowRetail_Covenant
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type CovenantIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func CovenantIndexField(input *CovenantIndexFields) *CovenantIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/index",
//			CnRegion:false ,
//}
//return input
//}


//CovenantIndex Returns an index of covenants.
//
//@see: /data/wow/covenant/index
func StringCovenantIndex(ctx context.Context, fields *CovenantIndexFields)(string,error){
	if fields == nil {
		fields = &CovenantIndexFields{}
	}

	func(input *CovenantIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCovenantIndex(ctx context.Context, fields *CovenantIndexFields)(any,error){

obj, err := StringCovenantIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&CovenantIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var CovenantIndex = CNCovenantIndex
/*func BNetCovenantIndex(ctx context.Context, fields *CovenantIndexFields)(any,error){

obj ,err := CNCovenantIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*CovenantIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type CovenantFields struct{
	CovenantId int//The ID of the covenant.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func CovenantField(input *CovenantFields) *CovenantFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/{covenantId}",
//			CnRegion:false ,
//}
//return input
//}


//Covenant Returns a covenant by ID.
//
//@see: /data/wow/covenant/{covenantId}
func StringCovenant(ctx context.Context, fields *CovenantFields)(string,error){
	if fields == nil {
		fields = &CovenantFields{}
	}

	func(input *CovenantFields) {
	
if input.CovenantId==0{
input.CovenantId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/{covenantId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("covenantId", strconv.Itoa(fields.CovenantId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCovenant(ctx context.Context, fields *CovenantFields)(any,error){

obj, err := StringCovenant(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&CovenantResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Covenant = CNCovenant
/*func BNetCovenant(ctx context.Context, fields *CovenantFields)(any,error){

obj ,err := CNCovenant(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*CovenantResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type CovenantMediaFields struct{
	CovenantId int//The ID of the covenant.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func CovenantMediaField(input *CovenantMediaFields) *CovenantMediaFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/media/covenant/{covenantId}",
//			CnRegion:false ,
//}
//return input
//}


//CovenantMedia Returns media for a covenant by ID.
//
//@see: /data/wow/media/covenant/{covenantId}
func StringCovenantMedia(ctx context.Context, fields *CovenantMediaFields)(string,error){
	if fields == nil {
		fields = &CovenantMediaFields{}
	}

	func(input *CovenantMediaFields) {
	
if input.CovenantId==0{
input.CovenantId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/media/covenant/{covenantId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("covenantId", strconv.Itoa(fields.CovenantId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCovenantMedia(ctx context.Context, fields *CovenantMediaFields)(any,error){

obj, err := StringCovenantMedia(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&CovenantMediaResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var CovenantMedia = CNCovenantMedia
/*func BNetCovenantMedia(ctx context.Context, fields *CovenantMediaFields)(any,error){

obj ,err := CNCovenantMedia(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*CovenantMediaResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type SoulbindIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SoulbindIndexField(input *SoulbindIndexFields) *SoulbindIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/soulbind/index",
//			CnRegion:false ,
//}
//return input
//}


//SoulbindIndex Returns an index of soulbinds.
//
//@see: /data/wow/covenant/soulbind/index
func StringSoulbindIndex(ctx context.Context, fields *SoulbindIndexFields)(string,error){
	if fields == nil {
		fields = &SoulbindIndexFields{}
	}

	func(input *SoulbindIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/soulbind/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSoulbindIndex(ctx context.Context, fields *SoulbindIndexFields)(any,error){

obj, err := StringSoulbindIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SoulbindIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var SoulbindIndex = CNSoulbindIndex
/*func BNetSoulbindIndex(ctx context.Context, fields *SoulbindIndexFields)(any,error){

obj ,err := CNSoulbindIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SoulbindIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type SoulbindFields struct{
	SoulbindId int//The ID of the soulbind.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SoulbindField(input *SoulbindFields) *SoulbindFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/soulbind/{soulbindId}",
//			CnRegion:false ,
//}
//return input
//}


//Soulbind Returns a soulbind by ID.
//
//@see: /data/wow/covenant/soulbind/{soulbindId}
func StringSoulbind(ctx context.Context, fields *SoulbindFields)(string,error){
	if fields == nil {
		fields = &SoulbindFields{}
	}

	func(input *SoulbindFields) {
	
if input.SoulbindId==0{
input.SoulbindId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/soulbind/{soulbindId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("soulbindId", strconv.Itoa(fields.SoulbindId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSoulbind(ctx context.Context, fields *SoulbindFields)(any,error){

obj, err := StringSoulbind(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SoulbindResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Soulbind = CNSoulbind
/*func BNetSoulbind(ctx context.Context, fields *SoulbindFields)(any,error){

obj ,err := CNSoulbind(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SoulbindResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type ConduitIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func ConduitIndexField(input *ConduitIndexFields) *ConduitIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/conduit/index",
//			CnRegion:false ,
//}
//return input
//}


//ConduitIndex Returns an index of conduits.
//
//@see: /data/wow/covenant/conduit/index
func StringConduitIndex(ctx context.Context, fields *ConduitIndexFields)(string,error){
	if fields == nil {
		fields = &ConduitIndexFields{}
	}

	func(input *ConduitIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/conduit/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNConduitIndex(ctx context.Context, fields *ConduitIndexFields)(any,error){

obj, err := StringConduitIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&ConduitIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var ConduitIndex = CNConduitIndex
/*func BNetConduitIndex(ctx context.Context, fields *ConduitIndexFields)(any,error){

obj ,err := CNConduitIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*ConduitIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type ConduitFields struct{
	ConduitId int//The ID of the conduit.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func ConduitField(input *ConduitFields) *ConduitFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/covenant/conduit/{conduitId}",
//			CnRegion:false ,
//}
//return input
//}


//Conduit Returns a conduit by ID.
//
//@see: /data/wow/covenant/conduit/{conduitId}
func StringConduit(ctx context.Context, fields *ConduitFields)(string,error){
	if fields == nil {
		fields = &ConduitFields{}
	}

	func(input *ConduitFields) {
	
if input.ConduitId==0{
input.ConduitId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/covenant/conduit/{conduitId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("conduitId", strconv.Itoa(fields.ConduitId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNConduit(ctx context.Context, fields *ConduitFields)(any,error){

obj, err := StringConduit(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&ConduitResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Conduit = CNConduit
/*func BNetConduit(ctx context.Context, fields *ConduitFields)(any,error){

obj ,err := CNConduit(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*ConduitResponse).ToBNet(),nil
}*/


