package wow_CharacterHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	
	    "strings"
    

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: CharacterHouseSummary
// ==============================================================================================

type CharacterHouseSummaryFields struct {
	RealmSlug string `uri:"realmSlug" binding:"required"` // The slug of the realm.
		CharacterName string `uri:"characterName" binding:"required"` // The lowercase name of the character.
		HouseNumber int `uri:"houseNumber" binding:"required"` // The number of the character's house.
		Namespace string `form:"namespace,default=profile-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookCharacterHouseSummary allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookCharacterHouseSummary func(context.Context, *CharacterHouseSummaryFields) (any, error)

// StringCharacterHouseSummary executes the request and returns the raw response body string.
func StringCharacterHouseSummary(ctx context.Context, fields *CharacterHouseSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterHouseSummaryFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("CharacterHouseSummary")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/house/house-{houseNumber}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.RealmSlug == "" {
		fields.RealmSlug = "tichondrius"
	}
	
	
	if fields.CharacterName == "" {
		fields.CharacterName = "charactername"
	}
	
	
	if fields.HouseNumber == 0 {
		fields.HouseNumber = 1
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "profile-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"realmSlug": fields.RealmSlug,
    		"characterName": fields.CharacterName,
    		"houseNumber": fields.HouseNumber,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "profile-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeCharacterHouseSummary routes the request to either CN or Global logic based on input.
func bridgeCharacterHouseSummary(ctx context.Context, fields *CharacterHouseSummaryFields) (any, error) {
    
	if strings.Contains(fields.Namespace, "-cn") {
		if fields.CN == nil {
			fields.CN = &utils.CNRequestMethod{
				
				Name:      fields.CharacterName,
				
				RealmSlug: fields.RealmSlug,
			}
		}
	}
	

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookCharacterHouseSummary != nil {
			return CNHookCharacterHouseSummary(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringCharacterHouseSummary(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &CharacterHouseSummaryModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// CharacterHouseSummary
/* CharacterHouseSummary Returns a summary of a house a character has built. */
// Path: /profile/wow/character/{realmSlug}/{characterName}/house/house-{houseNumber}
var CharacterHouseSummary = bridgeCharacterHouseSummary

