package SC_Ladder
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type GrandmasterLeaderboardFields struct{
	RegionId int//The region for the profile (`1`=US, `2`=EU, `3`=KO and TW, `5`=CN). 
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func GrandmasterLeaderboardField(input *GrandmasterLeaderboardFields) *GrandmasterLeaderboardFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/sc2/ladder/grandmaster/:regionId",
//			CnRegion:false ,
//}
//return input
//}


//GrandmasterLeaderboard Returns ladder data for the current season's grandmaster leaderboard.
//
//@see: /sc2/ladder/grandmaster/:regionId
func StringGrandmasterLeaderboard(ctx context.Context, fields *GrandmasterLeaderboardFields)(string,error){
	if fields == nil {
		fields = &GrandmasterLeaderboardFields{}
	}

	func(input *GrandmasterLeaderboardFields) {
	
if input.RegionId==0{
input.RegionId = <no value>
}
	
	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/sc2/ladder/grandmaster/:regionId",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("regionId", strconv.Itoa(fields.RegionId))
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGrandmasterLeaderboard(ctx context.Context, fields *GrandmasterLeaderboardFields)(any,error){

obj, err := StringGrandmasterLeaderboard(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&GrandmasterLeaderboardResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var GrandmasterLeaderboard = CNGrandmasterLeaderboard
/*func BNetGrandmasterLeaderboard(ctx context.Context, fields *GrandmasterLeaderboardFields)(any,error){

obj ,err := CNGrandmasterLeaderboard(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*GrandmasterLeaderboardResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type SeasonFields struct{
	RegionId int//The region for the profile (`1`=US, `2`=EU, `3`=KO and TW, `5`=CN). 
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func SeasonField(input *SeasonFields) *SeasonFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/sc2/ladder/season/:regionId",
//			CnRegion:false ,
//}
//return input
//}


//Season Returns data about the current season.
//
//@see: /sc2/ladder/season/:regionId
func StringSeason(ctx context.Context, fields *SeasonFields)(string,error){
	if fields == nil {
		fields = &SeasonFields{}
	}

	func(input *SeasonFields) {
	
if input.RegionId==0{
input.RegionId = <no value>
}
	
	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/sc2/ladder/season/:regionId",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("regionId", strconv.Itoa(fields.RegionId))
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNSeason(ctx context.Context, fields *SeasonFields)(any,error){

obj, err := StringSeason(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&SeasonResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Season = CNSeason
/*func BNetSeason(ctx context.Context, fields *SeasonFields)(any,error){

obj ,err := CNSeason(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*SeasonResponse).ToBNet(),nil
}*/


