package wowClassic_ConnectedRealm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	
	    "strconv"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: ConnectedRealmsIndex
// ==============================================================================================

type ConnectedRealmsIndexFields struct {
	Namespace string `form:"namespace,default=dynamic-classic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookConnectedRealmsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookConnectedRealmsIndex func(context.Context, *ConnectedRealmsIndexFields) (any, error)

// StringConnectedRealmsIndex executes the request and returns the raw response body string.
func StringConnectedRealmsIndex(ctx context.Context, fields *ConnectedRealmsIndexFields) (string, error) {
	if fields == nil {
		fields = &ConnectedRealmsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ConnectedRealmsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/connected-realm/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-classic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-classic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeConnectedRealmsIndex routes the request to either CN or Global logic based on input.
func bridgeConnectedRealmsIndex(ctx context.Context, fields *ConnectedRealmsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookConnectedRealmsIndex != nil {
			return CNHookConnectedRealmsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringConnectedRealmsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ConnectedRealmsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ConnectedRealmsIndex
/* ConnectedRealmsIndex Returns an index of connected realms. */
// Path: /data/wow/connected-realm/index
var ConnectedRealmsIndex = bridgeConnectedRealmsIndex


// ==============================================================================================
// API: ConnectedRealm
// ==============================================================================================

type ConnectedRealmFields struct {
	ConnectedRealmId int `uri:"connectedRealmId" binding:"required"` // The ID of the connected realm.
		Namespace string `form:"namespace,default=dynamic-classic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookConnectedRealm allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookConnectedRealm func(context.Context, *ConnectedRealmFields) (any, error)

// StringConnectedRealm executes the request and returns the raw response body string.
func StringConnectedRealm(ctx context.Context, fields *ConnectedRealmFields) (string, error) {
	if fields == nil {
		fields = &ConnectedRealmFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ConnectedRealm")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/connected-realm/{connectedRealmId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.ConnectedRealmId == 0 {
		fields.ConnectedRealmId = 4388
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-classic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"connectedRealmId": fields.ConnectedRealmId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-classic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeConnectedRealm routes the request to either CN or Global logic based on input.
func bridgeConnectedRealm(ctx context.Context, fields *ConnectedRealmFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookConnectedRealm != nil {
			return CNHookConnectedRealm(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringConnectedRealm(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ConnectedRealmModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ConnectedRealm
/* ConnectedRealm Returns a connected realm by ID. */
// Path: /data/wow/connected-realm/{connectedRealmId}
var ConnectedRealm = bridgeConnectedRealm


// ==============================================================================================
// API: ConnectedRealmsSearch
// ==============================================================================================

type ConnectedRealmsSearchFields struct {
	Namespace string `form:"namespace,default=dynamic-classic-us"` // The namespace to use to locate this document.
	Statustype string `form:"statustype,default=UP"` // The status of the connected realm, UP or DOWN. (example search field)
	Realmstimezone string `form:"realmstimezone,default=America/New_York"` // The timezone of the realm. (example search field)
	Orderby string `form:"orderby,default=id"` // The field to sort the result set by.
	_page int `form:"_page,default=1"` // The result page number.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookConnectedRealmsSearch allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookConnectedRealmsSearch func(context.Context, *ConnectedRealmsSearchFields) (any, error)

// StringConnectedRealmsSearch executes the request and returns the raw response body string.
func StringConnectedRealmsSearch(ctx context.Context, fields *ConnectedRealmsSearchFields) (string, error) {
	if fields == nil {
		fields = &ConnectedRealmsSearchFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("ConnectedRealmsSearch")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/search/connected-realm",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-classic-us"
	}
	
	
	if fields.Statustype == "" {
		fields.Statustype = "UP"
	}
	
	
	if fields.Realmstimezone == "" {
		fields.Realmstimezone = "America/New_York"
	}
	
	
	if fields.Orderby == "" {
		fields.Orderby = "id"
	}
	
	
	if fields._page == 0 {
		fields._page = 1
	}
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-classic-us")
	}
    
    
	if !q.Has("statustype") {
		q.Add("statustype", "UP")
	}
    
    
	if !q.Has("realmstimezone") {
		q.Add("realmstimezone", "America/New_York")
	}
    
    
	if !q.Has("orderby") {
		q.Add("orderby", "id")
	}
    
    
    	if !q.Has("_page") {
    		q.Add("_page", strconv.Itoa(fields._page))
    	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeConnectedRealmsSearch routes the request to either CN or Global logic based on input.
func bridgeConnectedRealmsSearch(ctx context.Context, fields *ConnectedRealmsSearchFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookConnectedRealmsSearch != nil {
			return CNHookConnectedRealmsSearch(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringConnectedRealmsSearch(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &ConnectedRealmsSearchModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// ConnectedRealmsSearch
/* ConnectedRealmsSearch Performs a search of connected realms. The fields below are provided for example. For more detail see the <a href="/documentation/world-of-warcraft-classic/guides/search">Search Guide</a>. */
// Path: /data/wow/search/connected-realm
var ConnectedRealmsSearch = bridgeConnectedRealmsSearch

