package wowClassic_PlayableClass
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPlayableClassMediaResponse is the unified BNet representation for PlayableClassMedia.
type BNetPlayableClassMediaResponse struct{}

// PlayableClassMediaResponse represents the raw CN API response for PlayableClassMedia.
type PlayableClassMediaResponse BNetPlayableClassMediaResponse

// ToBNet converts the CN response to the unified BNetPlayableClassMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PlayableClassMediaResponse) ToBNet() any {
	return r 
}

