package wowRetail_Item
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetItemSubclassResponse is the unified BNet representation for ItemSubclass.
type BNetItemSubclassResponse struct{}

// ItemSubclassResponse represents the raw CN API response for ItemSubclass.
type ItemSubclassResponse BNetItemSubclassResponse

// ToBNet converts the CN response to the unified BNetItemSubclassResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *ItemSubclassResponse) ToBNet() any {
	return r 
}

