package wowRetail_PowerType
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetPowerTypeResponse is the unified BNet representation for PowerType.
type BNetPowerTypeResponse struct{}

// PowerTypeResponse represents the raw CN API response for PowerType.
type PowerTypeResponse BNetPowerTypeResponse

// ToBNet converts the CN response to the unified BNetPowerTypeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *PowerTypeResponse) ToBNet() any {
	return r 
}

