package wow_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/jtacoma/uritemplates"
)

//==============================================================================================

type GuildFields struct {
	RealmSlug string //The slug of the realm.
	NameSlug  string //The slug of the guild.
	Namespace string //The namespace to use to locate this document.
	Locale    string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func GuildField(input *GuildFields) *GuildFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/guild/{realmSlug}/{nameSlug}",
//			CnRegion:false ,
//}
//return input
//}

func StringGuild(ctx context.Context, fields *GuildFields) (string, error) {
	if fields == nil {
		fields = &GuildFields{}
	}

	func(input *GuildFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.NameSlug == "" {
			input.NameSlug = "guild-slug"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/guild/{realmSlug}/{nameSlug}",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "nameSlug": fields.NameSlug})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("nameSlug", fields.NameSlug)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuild(ctx context.Context, fields *GuildFields) (any, error) {

	obj, err := cnStringGuild(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int            `json:"code"`
		Message string         `json:"message"`
		Data    *GuildResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringGuild(ctx context.Context, fields *GuildFields) (string, error) {
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/guildIndex", "realm_slug", fields.CN.RealmSlug, "guild_name", fields.CN.Name)
}

func bridgeGuild(ctx context.Context, fields *GuildFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNGuild(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*GuildResponse).ToBNet(), nil
	}
	obj, err := StringGuild(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetGuildResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// Guild Returns a single guild by its name and realm.
//
// @see: /data/wow/guild/{realmSlug}/{nameSlug}
var Guild = bridgeGuild

//==============================================================================================

type GuildActivityFields struct {
	RealmSlug string //The slug of the realm.
	NameSlug  string //The slug of the guild.
	Namespace string //The namespace to use to locate this document.
	Locale    string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func GuildActivityField(input *GuildActivityFields) *GuildActivityFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/guild/{realmSlug}/{nameSlug}/activity",
//			CnRegion:false ,
//}
//return input
//}

func StringGuildActivity(ctx context.Context, fields *GuildActivityFields) (string, error) {
	if fields == nil {
		fields = &GuildActivityFields{}
	}

	func(input *GuildActivityFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.NameSlug == "" {
			input.NameSlug = "guild-slug"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/guild/{realmSlug}/{nameSlug}/activity",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "nameSlug": fields.NameSlug})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("nameSlug", fields.NameSlug)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildActivity(ctx context.Context, fields *GuildActivityFields) (any, error) {

	obj, err := cnStringGuildActivity(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                    `json:"code"`
		Message string                 `json:"message"`
		Data    *GuildActivityResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringGuildActivity(ctx context.Context, fields *GuildActivityFields) (string, error) {
	return "", ApiError.ErrorNotSupported
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func bridgeGuildActivity(ctx context.Context, fields *GuildActivityFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNGuildActivity(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*GuildActivityResponse).ToBNet(), nil
	}
	obj, err := StringGuildActivity(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetGuildActivityResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// GuildActivity Returns a single guild's activity by name and realm.
//
// @see: /data/wow/guild/{realmSlug}/{nameSlug}/activity
var GuildActivity = bridgeGuildActivity

//==============================================================================================

type GuildAchievementsFields struct {
	RealmSlug string //The slug of the realm.
	NameSlug  string //The slug of the guild.
	Namespace string //The namespace to use to locate this document.
	Locale    string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func GuildAchievementsField(input *GuildAchievementsFields) *GuildAchievementsFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/guild/{realmSlug}/{nameSlug}/achievements",
//			CnRegion:false ,
//}
//return input
//}

func StringGuildAchievements(ctx context.Context, fields *GuildAchievementsFields) (string, error) {
	if fields == nil {
		fields = &GuildAchievementsFields{}
	}

	func(input *GuildAchievementsFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.NameSlug == "" {
			input.NameSlug = "guild-slug"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/guild/{realmSlug}/{nameSlug}/achievements",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "nameSlug": fields.NameSlug})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("nameSlug", fields.NameSlug)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildAchievements(ctx context.Context, fields *GuildAchievementsFields) (any, error) {

	obj, err := cnStringGuildAchievements(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                        `json:"code"`
		Message string                     `json:"message"`
		Data    *GuildAchievementsResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringGuildAchievements(ctx context.Context, fields *GuildAchievementsFields) (string, error) {
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "guild_achievement", "token", token)
}

func bridgeGuildAchievements(ctx context.Context, fields *GuildAchievementsFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNGuildAchievements(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*GuildAchievementsResponse).ToBNet(), nil
	}
	obj, err := StringGuildAchievements(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetGuildAchievementsResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// GuildAchievements Returns a single guild's achievements by name and realm.
//
// @see: /data/wow/guild/{realmSlug}/{nameSlug}/achievements
var GuildAchievements = bridgeGuildAchievements

//==============================================================================================

type GuildRosterFields struct {
	RealmSlug string //The slug of the realm.
	NameSlug  string //The slug of the guild.
	Namespace string //The namespace to use to locate this document.
	Locale    string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func GuildRosterField(input *GuildRosterFields) *GuildRosterFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/guild/{realmSlug}/{nameSlug}/roster",
//			CnRegion:false ,
//}
//return input
//}

func StringGuildRoster(ctx context.Context, fields *GuildRosterFields) (string, error) {
	if fields == nil {
		fields = &GuildRosterFields{}
	}

	func(input *GuildRosterFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.NameSlug == "" {
			input.NameSlug = "guild-slug"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/guild/{realmSlug}/{nameSlug}/roster",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "nameSlug": fields.NameSlug})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("nameSlug", fields.NameSlug)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNGuildRoster(ctx context.Context, fields *GuildRosterFields) (any, error) {

	obj, err := cnStringGuildRoster(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                  `json:"code"`
		Message string               `json:"message"`
		Data    *GuildRosterResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringGuildRoster(ctx context.Context, fields *GuildRosterFields) (string, error) {
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "guild_roster", "token", token)
}

func bridgeGuildRoster(ctx context.Context, fields *GuildRosterFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNGuildRoster(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*GuildRosterResponse).ToBNet(), nil
	}
	obj, err := StringGuildRoster(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetGuildRosterResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// GuildRoster Returns a single guild's roster by its name and realm.
//
// @see: /data/wow/guild/{realmSlug}/{nameSlug}/roster
var GuildRoster = bridgeGuildRoster
