package wow_CharacterTitles

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"

// BNetCharacterTitlesSummaryResponse is the unified BNet representation for CharacterTitlesSummary.
type BNetCharacterTitlesSummaryResponse struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Id    int    `json:"id"`
		Realm struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	Titles []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"titles"`
}

// CharacterTitlesSummaryResponse represents the raw CN API response for CharacterTitlesSummary.
type CharacterTitlesSummaryResponse struct{}

// ToBNet converts the CN response to the unified BNetCharacterTitlesSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CharacterTitlesSummaryResponse) ToBNet() any {
	return nil
}
