package wowRetail_MythicKeystoneDungeon
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetMythicKeystonePeriodsIndexResponse is the unified BNet representation for MythicKeystonePeriodsIndex.
type BNetMythicKeystonePeriodsIndexResponse struct{}

// MythicKeystonePeriodsIndexResponse represents the raw CN API response for MythicKeystonePeriodsIndex.
type MythicKeystonePeriodsIndexResponse BNetMythicKeystonePeriodsIndexResponse

// ToBNet converts the CN response to the unified BNetMythicKeystonePeriodsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *MythicKeystonePeriodsIndexResponse) ToBNet() any {
	return r 
}

