package wowRetail_MythicKeystoneDungeon
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetMythicKeystoneSeasonResponse is the unified BNet representation for MythicKeystoneSeason.
type BNetMythicKeystoneSeasonResponse struct{}

// MythicKeystoneSeasonResponse represents the raw CN API response for MythicKeystoneSeason.
type MythicKeystoneSeasonResponse BNetMythicKeystoneSeasonResponse

// ToBNet converts the CN response to the unified BNetMythicKeystoneSeasonResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *MythicKeystoneSeasonResponse) ToBNet() any {
	return r 
}

