package wowClassic_Region
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetRegionResponse is the unified BNet representation for Region.
type BNetRegionResponse struct{}

// RegionResponse represents the raw CN API response for Region.
type RegionResponse BNetRegionResponse

// ToBNet converts the CN response to the unified BNetRegionResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *RegionResponse) ToBNet() any {
	return r 
}

