package wow_CharacterProfessions

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance
import (
	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/bridge/client"
	"Unofficial_API/internal"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/jtacoma/uritemplates"
)

//==============================================================================================

type CharacterProfessionsSummaryFields struct {
	RealmSlug     string //The slug of the realm.
	CharacterName string //The lowercase name of the character.
	Namespace     string //The namespace to use to locate this document.
	Locale        string //The locale to reflect in localized data.

	ExtraFields map[any]any // extra fields
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

//func CharacterProfessionsSummaryField(input *CharacterProfessionsSummaryFields) *CharacterProfessionsSummaryFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/profile/wow/character/{realmSlug}/{characterName}/professions",
//			CnRegion:false ,
//}
//return input
//}

func StringCharacterProfessionsSummary(ctx context.Context, fields *CharacterProfessionsSummaryFields) (string, error) {
	if fields == nil {
		fields = &CharacterProfessionsSummaryFields{}
	}

	func(input *CharacterProfessionsSummaryFields) {

		if input.RealmSlug == "" {
			input.RealmSlug = "tichondrius"
		}

		if input.CharacterName == "" {
			input.CharacterName = "charactername"
		}

		if input.Namespace == "" {
			input.Namespace = "profile-us"
		}

		if input.Locale == "" {
			input.Locale = "en_US"
		}

		input.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/profile/wow/character/{realmSlug}/{characterName}/professions",
			CnRegion: false,
		}
	}(fields)
	cli := http.Client{}
	tpl, _ := uritemplates.Parse(fields.Path)
	u, _ := tpl.Expand(map[string]interface{}{"realmSlug": fields.RealmSlug, "characterName": fields.CharacterName})

	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+u,
		nil)

	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("realmSlug", fields.RealmSlug)
	q.Add("characterName", fields.CharacterName)
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)

	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNCharacterProfessionsSummary(ctx context.Context, fields *CharacterProfessionsSummaryFields) (any, error) {

	obj, err := cnStringCharacterProfessionsSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	var resp struct {
		Code    int                                  `json:"code"`
		Message string                               `json:"message"`
		Data    *CharacterProfessionsSummaryResponse `json:"data"`
	}

	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}

	return resp.Data, nil
}

func cnStringCharacterProfessionsSummary(ctx context.Context, fields *CharacterProfessionsSummaryFields) (string, error) {
	return "", ApiError.ErrorNotSupported
	token := internal.TryToGetToken(fields.CN.RealmSlug, fields.CN.Name)
	if token == "" {
		return "", ApiError.ErrorNoToken
	}
	return client.GET("https://webapi.blizzard.cn/wow-armory-server/api/do", "api", "", "token", token)
}

func bridgeCharacterProfessionsSummary(ctx context.Context, fields *CharacterProfessionsSummaryFields) (any, error) {

	if fields.CN != nil { // if no CN request parameters, use portal request instead
		obj, err := CNCharacterProfessionsSummary(ctx, fields)
		if err != nil {
			return nil, err
		}
		return obj.(*CharacterProfessionsSummaryResponse).ToBNet(), nil
	}
	obj, err := StringCharacterProfessionsSummary(ctx, fields)
	if err != nil {
		return nil, err
	}
	resp := &BNetCharacterProfessionsSummaryResponse{}
	err = json.Unmarshal([]byte(obj), &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil

}

// CharacterProfessionsSummary Returns a summary of professions for a character.
//
// @see: /profile/wow/character/{realmSlug}/{characterName}/professions
var CharacterProfessionsSummary = bridgeCharacterProfessionsSummary
