package wow_AccountProfile
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetProtectedCharacterProfileSummaryResponse is the unified BNet representation for ProtectedCharacterProfileSummary.
type BNetProtectedCharacterProfileSummaryResponse struct{}

// ProtectedCharacterProfileSummaryResponse represents the raw CN API response for ProtectedCharacterProfileSummary.
type ProtectedCharacterProfileSummaryResponse BNetProtectedCharacterProfileSummaryResponse

// ToBNet converts the CN response to the unified BNetProtectedCharacterProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *ProtectedCharacterProfileSummaryResponse) ToBNet() any {
	return r 
}

