package HeartStone_Cards
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetDetailedcardsearchexampleResponse is the unified BNet representation for Detailedcardsearchexample.
type BNetDetailedcardsearchexampleResponse struct{}

// DetailedcardsearchexampleResponse represents the raw CN API response for Detailedcardsearchexample.
type DetailedcardsearchexampleResponse BNetDetailedcardsearchexampleResponse

// ToBNet converts the CN response to the unified BNetDetailedcardsearchexampleResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *DetailedcardsearchexampleResponse) ToBNet() any {
	return r 
}

