package wow_MythicKeystoneLeaderboard

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: MythicKeystoneLeaderboardsIndex
// ==============================================================================================

type MythicKeystoneLeaderboardsIndexFields struct {
	ConnectedRealmId int `uri:"connectedRealmId" binding:"required"` // The ID of the connected realm.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookMythicKeystoneLeaderboardsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookMythicKeystoneLeaderboardsIndex func(context.Context, *MythicKeystoneLeaderboardsIndexFields) (any, error)

// StringMythicKeystoneLeaderboardsIndex executes the request and returns the raw response body string.
func StringMythicKeystoneLeaderboardsIndex(ctx context.Context, fields *MythicKeystoneLeaderboardsIndexFields) (string, error) {
	if fields == nil {
		fields = &MythicKeystoneLeaderboardsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("MythicKeystoneLeaderboardsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.ConnectedRealmId == 0 {
		fields.ConnectedRealmId = 11
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"connectedRealmId": fields.ConnectedRealmId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeMythicKeystoneLeaderboardsIndex routes the request to either CN or Global logic based on input.
func bridgeMythicKeystoneLeaderboardsIndex(ctx context.Context, fields *MythicKeystoneLeaderboardsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookMythicKeystoneLeaderboardsIndex != nil {
			return CNHookMythicKeystoneLeaderboardsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringMythicKeystoneLeaderboardsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &MythicKeystoneLeaderboardsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// MythicKeystoneLeaderboardsIndex
/* MythicKeystoneLeaderboardsIndex Returns an index of Mythic Keystone Leaderboard dungeon instances for a connected realm. */
// Path: /data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/index
var MythicKeystoneLeaderboardsIndex = bridgeMythicKeystoneLeaderboardsIndex


// ==============================================================================================
// API: MythicKeystoneLeaderboard
// ==============================================================================================

type MythicKeystoneLeaderboardFields struct {
	ConnectedRealmId int `uri:"connectedRealmId" binding:"required"` // The ID of the connected realm.
		DungeonId int `uri:"dungeonId" binding:"required"` // The ID of the dungeon.
		Period int `uri:"period" binding:"required"` // The unique identifier for the leaderboard period.
		Namespace string `form:"namespace,default=dynamic-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookMythicKeystoneLeaderboard allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookMythicKeystoneLeaderboard func(context.Context, *MythicKeystoneLeaderboardFields) (any, error)

// StringMythicKeystoneLeaderboard executes the request and returns the raw response body string.
func StringMythicKeystoneLeaderboard(ctx context.Context, fields *MythicKeystoneLeaderboardFields) (string, error) {
	if fields == nil {
		fields = &MythicKeystoneLeaderboardFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("MythicKeystoneLeaderboard")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/{dungeonId}/period/{period}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.ConnectedRealmId == 0 {
		fields.ConnectedRealmId = 11
	}
	
	if fields.DungeonId == 0 {
		fields.DungeonId = 197
	}
	
	if fields.Period == 0 {
		fields.Period = 641
	}
	
	if fields.Namespace == "" {
		fields.Namespace = "dynamic-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"connectedRealmId": fields.ConnectedRealmId,
    		"dungeonId": fields.DungeonId,
    		"period": fields.Period,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "dynamic-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeMythicKeystoneLeaderboard routes the request to either CN or Global logic based on input.
func bridgeMythicKeystoneLeaderboard(ctx context.Context, fields *MythicKeystoneLeaderboardFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookMythicKeystoneLeaderboard != nil {
			return CNHookMythicKeystoneLeaderboard(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringMythicKeystoneLeaderboard(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &MythicKeystoneLeaderboardModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// MythicKeystoneLeaderboard
/* MythicKeystoneLeaderboard Returns a weekly Mythic Keystone Leaderboard by period. */
// Path: /data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/{dungeonId}/period/{period}
var MythicKeystoneLeaderboard = bridgeMythicKeystoneLeaderboard

