package wowRetail_MythicKeystoneLeaderboard
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetMythicKeystoneLeaderboardResponse is the unified BNet representation for MythicKeystoneLeaderboard.
type BNetMythicKeystoneLeaderboardResponse struct{}

// MythicKeystoneLeaderboardResponse represents the raw CN API response for MythicKeystoneLeaderboard.
type MythicKeystoneLeaderboardResponse BNetMythicKeystoneLeaderboardResponse

// ToBNet converts the CN response to the unified BNetMythicKeystoneLeaderboardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *MythicKeystoneLeaderboardResponse) ToBNet() any {
	return r 
}

