package wowRetail_Title
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type TitlesIndexFields struct{
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func TitlesIndexField(input *TitlesIndexFields) *TitlesIndexFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/title/index",
//			CnRegion:false ,
//}
//return input
//}


//TitlesIndex Returns an index of titles.
//
//@see: /data/wow/title/index
func StringTitlesIndex(ctx context.Context, fields *TitlesIndexFields)(string,error){
	if fields == nil {
		fields = &TitlesIndexFields{}
	}

	func(input *TitlesIndexFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/title/index",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNTitlesIndex(ctx context.Context, fields *TitlesIndexFields)(any,error){

obj, err := StringTitlesIndex(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&TitlesIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var TitlesIndex = CNTitlesIndex
/*func BNetTitlesIndex(ctx context.Context, fields *TitlesIndexFields)(any,error){

obj ,err := CNTitlesIndex(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*TitlesIndexResponse).ToBNet(),nil
}*/

 
//==============================================================================================

type TitleFields struct{
	TitleId int//The ID of the title.
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func TitleField(input *TitleFields) *TitleFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/title/{titleId}",
//			CnRegion:false ,
//}
//return input
//}


//Title Returns a title by ID.
//
//@see: /data/wow/title/{titleId}
func StringTitle(ctx context.Context, fields *TitleFields)(string,error){
	if fields == nil {
		fields = &TitleFields{}
	}

	func(input *TitleFields) {
	
if input.TitleId==0{
input.TitleId = 1
}
	
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Locale==""{
input.Locale = "en_US"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/title/{titleId}",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("titleId", strconv.Itoa(fields.TitleId))
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNTitle(ctx context.Context, fields *TitleFields)(any,error){

obj, err := StringTitle(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&TitleResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var Title = CNTitle
/*func BNetTitle(ctx context.Context, fields *TitleFields)(any,error){

obj ,err := CNTitle(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*TitleResponse).ToBNet(),nil
}*/


