package SC_Legacy
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

//import "github.com/jinzhu/copier"


// BNetLaddersResponse is the unified BNet representation for Ladders.
type BNetLaddersResponse struct{}

// LaddersResponse represents the raw CN API response for Ladders.
type LaddersResponse BNetLaddersResponse

// ToBNet converts the CN response to the unified BNetLaddersResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *LaddersResponse) ToBNet() any {
	return r 
}

