package wow_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance

import (
	"context"
	"encoding/json"
	

	

	"io"
	"net/http"

	"Unofficial_API/ApiError"
	"Unofficial_API/api/Authentication"
	"Unofficial_API/global"
	"Unofficial_API/utils"


	"github.com/jtacoma/uritemplates"

)


// ==============================================================================================
// API: GuildCrestComponentsIndex
// ==============================================================================================

type GuildCrestComponentsIndexFields struct {
	Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookGuildCrestComponentsIndex allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookGuildCrestComponentsIndex func(context.Context, *GuildCrestComponentsIndexFields) (any, error)

// StringGuildCrestComponentsIndex executes the request and returns the raw response body string.
func StringGuildCrestComponentsIndex(ctx context.Context, fields *GuildCrestComponentsIndexFields) (string, error) {
	if fields == nil {
		fields = &GuildCrestComponentsIndexFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("GuildCrestComponentsIndex")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/guild-crest/index",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	req.URL.Path = fields.Path
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeGuildCrestComponentsIndex routes the request to either CN or Global logic based on input.
func bridgeGuildCrestComponentsIndex(ctx context.Context, fields *GuildCrestComponentsIndexFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookGuildCrestComponentsIndex != nil {
			return CNHookGuildCrestComponentsIndex(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringGuildCrestComponentsIndex(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &GuildCrestComponentsIndexModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GuildCrestComponentsIndex
/* GuildCrestComponentsIndex Returns an index of guild crest media. */
// Path: /data/wow/guild-crest/index
var GuildCrestComponentsIndex = bridgeGuildCrestComponentsIndex


// ==============================================================================================
// API: GuildCrestBorderMedia
// ==============================================================================================

type GuildCrestBorderMediaFields struct {
	BorderId int `uri:"borderId" binding:"required"` // The ID of the guild crest border.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookGuildCrestBorderMedia allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookGuildCrestBorderMedia func(context.Context, *GuildCrestBorderMediaFields) (any, error)

// StringGuildCrestBorderMedia executes the request and returns the raw response body string.
func StringGuildCrestBorderMedia(ctx context.Context, fields *GuildCrestBorderMediaFields) (string, error) {
	if fields == nil {
		fields = &GuildCrestBorderMediaFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("GuildCrestBorderMedia")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/media/guild-crest/border/{borderId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"borderId": fields.BorderId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeGuildCrestBorderMedia routes the request to either CN or Global logic based on input.
func bridgeGuildCrestBorderMedia(ctx context.Context, fields *GuildCrestBorderMediaFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookGuildCrestBorderMedia != nil {
			return CNHookGuildCrestBorderMedia(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringGuildCrestBorderMedia(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &GuildCrestBorderMediaModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GuildCrestBorderMedia
/* GuildCrestBorderMedia Returns media for a guild crest border by ID. */
// Path: /data/wow/media/guild-crest/border/{borderId}
var GuildCrestBorderMedia = bridgeGuildCrestBorderMedia


// ==============================================================================================
// API: GuildCrestEmblemMedia
// ==============================================================================================

type GuildCrestEmblemMediaFields struct {
	EmblemId int `uri:"emblemId" binding:"required"` // The ID of the guild crest emblem.
		Namespace string `form:"namespace,default=static-us"` // The namespace to use to locate this document.
	Locale string `form:"locale,default=en_US"` // The locale to reflect in localized data.

	// Extra fields for internal logic
	ExtraFields map[any]any
	CN          *utils.CNRequestMethod
	utils.RequestMethod
}

// CNHookGuildCrestEmblemMedia allows injecting a custom implementation for the CN endpoint.
// Implement this in a separate file (e.g. init()) to handle CN logic without modifying generated code.
var CNHookGuildCrestEmblemMedia func(context.Context, *GuildCrestEmblemMediaFields) (any, error)

// StringGuildCrestEmblemMedia executes the request and returns the raw response body string.
func StringGuildCrestEmblemMedia(ctx context.Context, fields *GuildCrestEmblemMediaFields) (string, error) {
	if fields == nil {
		fields = &GuildCrestEmblemMediaFields{}
	}

	// 1. Initialize Request Metadata
	fields.RequestMethod = utils.GetApiConfig("GuildCrestEmblemMedia")
	if fields.RequestMethod.Path == "" {
		fields.RequestMethod = utils.RequestMethod{
			Methods:  "GET",
			Path:     "/data/wow/media/guild-crest/emblem/{emblemId}",
			CnRegion: false,
		}
	}

	// 2. Apply Default Values (if needed for client-side logic)
	// Note: Usually struct tags handle server-side binding,
	// but here we might need manual checks if 0/"" are invalid for the request.
	
	if fields.Namespace == "" {
		fields.Namespace = "static-us"
	}
	
	
	if fields.Locale == "" {
		fields.Locale = "en_US"
	}
	
	

	// 3. Create HTTP Request
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		global.PortalURL, // Base URL will be joined with Path below
		nil,
	)
	if err != nil {
		return "", err
	}

	// Add Auth Header
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())

	// 4. Resolve Path (Handle URI Bindings)
	{
	
    	tpl, err := uritemplates.Parse(fields.Path)
    	if err != nil {
    		return "", err
    	}

    	pathValues := map[string]interface{}{
    		"emblemId": fields.EmblemId,
    		
    	}

    	expandedPath, err := tpl.Expand(pathValues)
    	if err != nil {
    		return "", err
    	}
    	req.URL.Path = expandedPath
    	
	}

	// 5. Build Query Strings
{
	q := req.URL.Query()


	for key, value := range fields.ExtraFields {
		q.Add(key.(string), value.(string))
	}

	
    
	if !q.Has("namespace") {
		q.Add("namespace", "static-us")
	}
    
    
	if !q.Has("locale") {
		q.Add("locale", "en_US")
	}
    


	req.URL.RawQuery = q.Encode()
}

	// 6. Execute Request
	cli := http.Client{}
	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

// bridgeGuildCrestEmblemMedia routes the request to either CN or Global logic based on input.
func bridgeGuildCrestEmblemMedia(ctx context.Context, fields *GuildCrestEmblemMediaFields) (any, error) {
    

	// 1. If CN specific parameters are present, use CN logic
	if fields.CN != nil {
        // Design Scheme: Check if a custom CN handler is registered at runtime.
		// This allows extension without modifying the template generator.
		if CNHookGuildCrestEmblemMedia != nil {
			return CNHookGuildCrestEmblemMedia(ctx, fields)
		}

		return nil, ApiError.ErrorNotSupported
	}

	// 2. Default: Use Global/Standard logic
	objString, err := StringGuildCrestEmblemMedia(ctx, fields)
	if err != nil {
		return nil, err
	}

	resp := &GuildCrestEmblemMediaModel{}
	if err = json.Unmarshal([]byte(objString), &resp); err != nil {
		return nil, err
	}

	return resp, nil
}

// GuildCrestEmblemMedia
/* GuildCrestEmblemMedia Returns media for a guild crest emblem by ID. */
// Path: /data/wow/media/guild-crest/emblem/{emblemId}
var GuildCrestEmblemMedia = bridgeGuildCrestEmblemMedia

