package wowClassic_MediaSearch
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
)

 
//==============================================================================================

type MediaSearchFields struct{
	Namespace string//The namespace to use to locate this document.
	Tags string//The media document type as derived from the URL. For example, /wow/media/item/{id} will have tag 'item'. (example search field)
	Orderby string//The field to sort the result set by.
	_page int//The result page number.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func MediaSearchField(input *MediaSearchFields) *MediaSearchFields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/search/media",
//			CnRegion:false ,
//}
//return input
//}


//MediaSearch Performs a search of all types of media documents. The fields below are provided for example. For more detail see the <a href="/documentation/world-of-warcraft/guides/search">Search Guide</a>.
//
//@see: /data/wow/search/media
func StringMediaSearch(ctx context.Context, fields *MediaSearchFields)(string,error){
	if fields == nil {
		fields = &MediaSearchFields{}
	}

	func(input *MediaSearchFields) {
	
if input.Namespace==""{
input.Namespace = "static-us"
}

	
if input.Tags==""{
input.Tags = "item"
}

	
if input.Orderby==""{
input.Orderby = "id"
}

	
if input._page==0{
input._page = 1
}
	
	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/search/media",
			CnRegion:false ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("tags", fields.Tags)
	q.Add("orderby", fields.Orderby)
	q.Add("_page", strconv.Itoa(fields._page))
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNMediaSearch(ctx context.Context, fields *MediaSearchFields)(any,error){

obj, err := StringMediaSearch(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&MediaSearchResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var MediaSearch = CNMediaSearch
/*func BNetMediaSearch(ctx context.Context, fields *MediaSearchFields)(any,error){

obj ,err := CNMediaSearch(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*MediaSearchResponse).ToBNet(),nil
}*/


